module ichdecision_interface (
    input logic [5:0] adj_predicted_size,
    input logic [5:0] alt_pfx,
    input logic [5:0] alt_size_to_generate,
    input logic [1:0] dsc_version_minor,
    input logic native_420,
    input logic [9:0] flatness_det_thresh,
    input logic [2:0] somewhat_flat_qp_delta,
    input logic [2:0] units_per_group,
    input logic [1:0] pixels_in_group,
    input logic [15:0] hPos,
    input logic [15:0] slice_width,
    input logic prev_ich_selected,
    input logic [4:0] primary_qp,
    input logic [4:0] prev_primary_qp,
    input logic [2:0] ich_indices_in_group,
    input logic [2:0] num_components,
    input logic [4:0] cpnt_bit_depth_0,
    input logic [4:0] cpnt_bit_depth_1,
    input logic [4:0] cpnt_bit_depth_2,
    input logic [4:0] cpnt_bit_depth_3,
    input logic [1:0] unit_c_type_0,
    input logic [1:0] unit_c_type_1,
    input logic [1:0] unit_c_type_2,
    input logic [1:0] unit_c_type_3,
    input logic [15:0] unit_start_h_pos_0,
    input logic [15:0] unit_start_h_pos_1,
    input logic [15:0] unit_start_h_pos_2,
    input logic [15:0] unit_start_h_pos_3,
    input logic [4:0] predicted_size_0,
    input logic [4:0] predicted_size_1,
    input logic [4:0] predicted_size_2,
    input logic [4:0] predicted_size_3,
    input logic [16:0] max_error_0,
    input logic [16:0] max_error_1,
    input logic [16:0] max_error_2,
    input logic [16:0] max_error_3,
    input logic [16:0] max_mid_error_0,
    input logic [16:0] max_mid_error_1,
    input logic [16:0] max_mid_error_2,
    input logic [16:0] max_mid_error_3,
    input logic [16:0] max_ich_error_0,
    input logic [16:0] max_ich_error_1,
    input logic [16:0] max_ich_error_2,
    input logic [16:0] max_ich_error_3,
    input logic signed [16:0] quantized_residual_0_0,
    input logic signed [16:0] quantized_residual_0_1,
    input logic signed [16:0] quantized_residual_0_2,
    input logic signed [16:0] quantized_residual_1_0,
    input logic signed [16:0] quantized_residual_1_1,
    input logic signed [16:0] quantized_residual_1_2,
    input logic signed [16:0] quantized_residual_2_0,
    input logic signed [16:0] quantized_residual_2_1,
    input logic signed [16:0] quantized_residual_2_2,
    input logic signed [16:0] quantized_residual_3_0,
    input logic signed [16:0] quantized_residual_3_1,
    input logic signed [16:0] quantized_residual_3_2,
    input logic [4:0] qlevel_luma_primary,
    input logic [4:0] qlevel_chroma_primary,
    input logic [4:0] qlevel_luma_previous,
    input logic [4:0] qlevel_chroma_previous,
    input logic [4:0] qlevel_luma_flat,
    input logic [4:0] qlevel_chroma_flat,
    input logic [15:0] orig_0_0,
    input logic [15:0] orig_0_1,
    input logic [15:0] orig_0_2,
    input logic [15:0] orig_0_3,
    input logic [15:0] orig_0_4,
    input logic [15:0] orig_0_5,
    input logic [15:0] orig_0_6,
    input logic [15:0] orig_1_0,
    input logic [15:0] orig_1_1,
    input logic [15:0] orig_1_2,
    input logic [15:0] orig_1_3,
    input logic [15:0] orig_1_4,
    input logic [15:0] orig_1_5,
    input logic [15:0] orig_1_6,
    input logic [15:0] orig_2_0,
    input logic [15:0] orig_2_1,
    input logic [15:0] orig_2_2,
    input logic [15:0] orig_2_3,
    input logic [15:0] orig_2_4,
    input logic [15:0] orig_2_5,
    input logic [15:0] orig_2_6,
    input logic [15:0] orig_3_0,
    input logic [15:0] orig_3_1,
    input logic [15:0] orig_3_2,
    input logic [15:0] orig_3_3,
    input logic [15:0] orig_3_4,
    input logic [15:0] orig_3_5,
    input logic [15:0] orig_3_6,
    output logic return_value
);
endmodule
