#include <stdio.h>
#include <string.h>
#include "dsc_types.h"
extern int IchDecision(dsc_cfg_t *, dsc_state_t *, int, int, int);
int main(int argc, char **argv) {
    FILE *input = stdin;
    if (argc > 1) {
        input = fopen(argv[1], "rb");
        if (!input) return 2;
    }
    int adj_predicted_size, alt_pfx, alt_size_to_generate, dsc_version_minor, native_420, flatness_det_thresh, somewhat_flat_qp_delta, units_per_group, pixels_in_group, hPos, slice_width, prev_ich_selected, primary_qp, prev_primary_qp, ich_indices_in_group, num_components, cpnt_bit_depth_0, cpnt_bit_depth_1, cpnt_bit_depth_2, cpnt_bit_depth_3, unit_c_type_0, unit_c_type_1, unit_c_type_2, unit_c_type_3, unit_start_h_pos_0, unit_start_h_pos_1, unit_start_h_pos_2, unit_start_h_pos_3, predicted_size_0, predicted_size_1, predicted_size_2, predicted_size_3, max_error_0, max_error_1, max_error_2, max_error_3, max_mid_error_0, max_mid_error_1, max_mid_error_2, max_mid_error_3, max_ich_error_0, max_ich_error_1, max_ich_error_2, max_ich_error_3, quantized_residual_0_0, quantized_residual_0_1, quantized_residual_0_2, quantized_residual_1_0, quantized_residual_1_1, quantized_residual_1_2, quantized_residual_2_0, quantized_residual_2_1, quantized_residual_2_2, quantized_residual_3_0, quantized_residual_3_1, quantized_residual_3_2, qlevel_luma_primary, qlevel_chroma_primary, qlevel_luma_previous, qlevel_chroma_previous, qlevel_luma_flat, qlevel_chroma_flat, orig_0_0, orig_0_1, orig_0_2, orig_0_3, orig_0_4, orig_0_5, orig_0_6, orig_1_0, orig_1_1, orig_1_2, orig_1_3, orig_1_4, orig_1_5, orig_1_6, orig_2_0, orig_2_1, orig_2_2, orig_2_3, orig_2_4, orig_2_5, orig_2_6, orig_3_0, orig_3_1, orig_3_2, orig_3_3, orig_3_4, orig_3_5, orig_3_6;
    int return_value;
    while (fscanf(input, "%d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d", &adj_predicted_size, &alt_pfx, &alt_size_to_generate, &dsc_version_minor, &native_420, &flatness_det_thresh, &somewhat_flat_qp_delta, &units_per_group, &pixels_in_group, &hPos, &slice_width, &prev_ich_selected, &primary_qp, &prev_primary_qp, &ich_indices_in_group, &num_components, &cpnt_bit_depth_0, &cpnt_bit_depth_1, &cpnt_bit_depth_2, &cpnt_bit_depth_3, &unit_c_type_0, &unit_c_type_1, &unit_c_type_2, &unit_c_type_3, &unit_start_h_pos_0, &unit_start_h_pos_1, &unit_start_h_pos_2, &unit_start_h_pos_3, &predicted_size_0, &predicted_size_1, &predicted_size_2, &predicted_size_3, &max_error_0, &max_error_1, &max_error_2, &max_error_3, &max_mid_error_0, &max_mid_error_1, &max_mid_error_2, &max_mid_error_3, &max_ich_error_0, &max_ich_error_1, &max_ich_error_2, &max_ich_error_3, &quantized_residual_0_0, &quantized_residual_0_1, &quantized_residual_0_2, &quantized_residual_1_0, &quantized_residual_1_1, &quantized_residual_1_2, &quantized_residual_2_0, &quantized_residual_2_1, &quantized_residual_2_2, &quantized_residual_3_0, &quantized_residual_3_1, &quantized_residual_3_2, &qlevel_luma_primary, &qlevel_chroma_primary, &qlevel_luma_previous, &qlevel_chroma_previous, &qlevel_luma_flat, &qlevel_chroma_flat, &orig_0_0, &orig_0_1, &orig_0_2, &orig_0_3, &orig_0_4, &orig_0_5, &orig_0_6, &orig_1_0, &orig_1_1, &orig_1_2, &orig_1_3, &orig_1_4, &orig_1_5, &orig_1_6, &orig_2_0, &orig_2_1, &orig_2_2, &orig_2_3, &orig_2_4, &orig_2_5, &orig_2_6, &orig_3_0, &orig_3_1, &orig_3_2, &orig_3_3, &orig_3_4, &orig_3_5, &orig_3_6) == 90) {
        dsc_cfg_t dsc_cfg = {0};
            dsc_state_t dsc_state = {0};
            int quant_luma[32] = {0};
            int quant_chroma[32] = {0};
            static int orig_line[NUM_COMPONENTS][PADDING_LEFT + 65535 + 8];
        dsc_cfg.dsc_version_minor = dsc_version_minor;
            dsc_cfg.native_420 = native_420;
            dsc_cfg.flatness_det_thresh = flatness_det_thresh;
            dsc_cfg.somewhat_flat_qp_delta = somewhat_flat_qp_delta;
            dsc_state.unitsPerGroup = units_per_group;
            dsc_state.pixelsInGroup = pixels_in_group;
            dsc_state.hPos = hPos;
            dsc_state.sliceWidth = slice_width;
            dsc_state.prevIchSelected = prev_ich_selected;
            dsc_state.primaryQp = primary_qp;
            dsc_state.prevPrimaryQp = prev_primary_qp;
            dsc_state.ichIndicesInGroup = ich_indices_in_group;
            dsc_state.numComponents = num_components;
            dsc_state.cpntBitDepth[0] = cpnt_bit_depth_0;
            dsc_state.cpntBitDepth[1] = cpnt_bit_depth_1;
            dsc_state.cpntBitDepth[2] = cpnt_bit_depth_2;
            dsc_state.cpntBitDepth[3] = cpnt_bit_depth_3;
            dsc_state.unitCType[0] = unit_c_type_0;
            dsc_state.unitCType[1] = unit_c_type_1;
            dsc_state.unitCType[2] = unit_c_type_2;
            dsc_state.unitCType[3] = unit_c_type_3;
            dsc_state.unitStartHPos[0] = unit_start_h_pos_0;
            dsc_state.unitStartHPos[1] = unit_start_h_pos_1;
            dsc_state.unitStartHPos[2] = unit_start_h_pos_2;
            dsc_state.unitStartHPos[3] = unit_start_h_pos_3;
            dsc_state.predictedSize[0] = predicted_size_0;
            dsc_state.predictedSize[1] = predicted_size_1;
            dsc_state.predictedSize[2] = predicted_size_2;
            dsc_state.predictedSize[3] = predicted_size_3;
            dsc_state.maxError[0] = max_error_0;
            dsc_state.maxError[1] = max_error_1;
            dsc_state.maxError[2] = max_error_2;
            dsc_state.maxError[3] = max_error_3;
            dsc_state.maxMidError[0] = max_mid_error_0;
            dsc_state.maxMidError[1] = max_mid_error_1;
            dsc_state.maxMidError[2] = max_mid_error_2;
            dsc_state.maxMidError[3] = max_mid_error_3;
            dsc_state.maxIchError[0] = max_ich_error_0;
            dsc_state.maxIchError[1] = max_ich_error_1;
            dsc_state.maxIchError[2] = max_ich_error_2;
            dsc_state.maxIchError[3] = max_ich_error_3;
            dsc_state.quantizedResidual[0][0] = quantized_residual_0_0;
            dsc_state.quantizedResidual[0][1] = quantized_residual_0_1;
            dsc_state.quantizedResidual[0][2] = quantized_residual_0_2;
            dsc_state.quantizedResidual[1][0] = quantized_residual_1_0;
            dsc_state.quantizedResidual[1][1] = quantized_residual_1_1;
            dsc_state.quantizedResidual[1][2] = quantized_residual_1_2;
            dsc_state.quantizedResidual[2][0] = quantized_residual_2_0;
            dsc_state.quantizedResidual[2][1] = quantized_residual_2_1;
            dsc_state.quantizedResidual[2][2] = quantized_residual_2_2;
            dsc_state.quantizedResidual[3][0] = quantized_residual_3_0;
            dsc_state.quantizedResidual[3][1] = quantized_residual_3_1;
            dsc_state.quantizedResidual[3][2] = quantized_residual_3_2;
            dsc_state.quantTableLuma = quant_luma;
            dsc_state.quantTableChroma = quant_chroma;
            for (int table_i = 0; table_i < 32; ++table_i) { quant_luma[table_i] = 0; quant_chroma[table_i] = 0; }
            quant_luma[primary_qp] = qlevel_luma_primary;
            quant_chroma[primary_qp] = qlevel_chroma_primary;
            quant_luma[prev_primary_qp] = qlevel_luma_previous;
            quant_chroma[prev_primary_qp] = qlevel_chroma_previous;
            int flat_qp = primary_qp - somewhat_flat_qp_delta;
            if (flat_qp < 0) flat_qp = 0;
            quant_luma[flat_qp] = qlevel_luma_flat;
            quant_chroma[flat_qp] = qlevel_chroma_flat;
            dsc_state.origLine[0] = orig_line[0];
            dsc_state.origLine[1] = orig_line[1];
            dsc_state.origLine[2] = orig_line[2];
            dsc_state.origLine[3] = orig_line[3];
            orig_line[0][PADDING_LEFT + hPos + 0] = orig_0_0;
            orig_line[0][PADDING_LEFT + hPos + 1] = orig_0_1;
            orig_line[0][PADDING_LEFT + hPos + 2] = orig_0_2;
            orig_line[0][PADDING_LEFT + hPos + 3] = orig_0_3;
            orig_line[0][PADDING_LEFT + hPos + 4] = orig_0_4;
            orig_line[0][PADDING_LEFT + hPos + 5] = orig_0_5;
            orig_line[0][PADDING_LEFT + hPos + 6] = orig_0_6;
            orig_line[1][PADDING_LEFT + hPos + 0] = orig_1_0;
            orig_line[1][PADDING_LEFT + hPos + 1] = orig_1_1;
            orig_line[1][PADDING_LEFT + hPos + 2] = orig_1_2;
            orig_line[1][PADDING_LEFT + hPos + 3] = orig_1_3;
            orig_line[1][PADDING_LEFT + hPos + 4] = orig_1_4;
            orig_line[1][PADDING_LEFT + hPos + 5] = orig_1_5;
            orig_line[1][PADDING_LEFT + hPos + 6] = orig_1_6;
            orig_line[2][PADDING_LEFT + hPos + 0] = orig_2_0;
            orig_line[2][PADDING_LEFT + hPos + 1] = orig_2_1;
            orig_line[2][PADDING_LEFT + hPos + 2] = orig_2_2;
            orig_line[2][PADDING_LEFT + hPos + 3] = orig_2_3;
            orig_line[2][PADDING_LEFT + hPos + 4] = orig_2_4;
            orig_line[2][PADDING_LEFT + hPos + 5] = orig_2_5;
            orig_line[2][PADDING_LEFT + hPos + 6] = orig_2_6;
            orig_line[3][PADDING_LEFT + hPos + 0] = orig_3_0;
            orig_line[3][PADDING_LEFT + hPos + 1] = orig_3_1;
            orig_line[3][PADDING_LEFT + hPos + 2] = orig_3_2;
            orig_line[3][PADDING_LEFT + hPos + 3] = orig_3_3;
            orig_line[3][PADDING_LEFT + hPos + 4] = orig_3_4;
            orig_line[3][PADDING_LEFT + hPos + 5] = orig_3_5;
            orig_line[3][PADDING_LEFT + hPos + 6] = orig_3_6;
            dsc_state.quantizedResidual[0][0] = quantized_residual_0_0;
            dsc_state.quantizedResidual[0][1] = quantized_residual_0_1;
            dsc_state.quantizedResidual[0][2] = quantized_residual_0_2;
            dsc_state.quantizedResidual[1][0] = quantized_residual_1_0;
            dsc_state.quantizedResidual[1][1] = quantized_residual_1_1;
            dsc_state.quantizedResidual[1][2] = quantized_residual_1_2;
            dsc_state.quantizedResidual[2][0] = quantized_residual_2_0;
            dsc_state.quantizedResidual[2][1] = quantized_residual_2_1;
            dsc_state.quantizedResidual[2][2] = quantized_residual_2_2;
            dsc_state.quantizedResidual[3][0] = quantized_residual_3_0;
            dsc_state.quantizedResidual[3][1] = quantized_residual_3_1;
            dsc_state.quantizedResidual[3][2] = quantized_residual_3_2;
        return_value = IchDecision(&dsc_cfg, &dsc_state, adj_predicted_size, alt_pfx, alt_size_to_generate);
        printf("%d\n", return_value);
    }
    if (input != stdin) fclose(input);
    return 0;
}
