// Generated by tools/generate_process_group_encode.py
// Encoder-only bounded FSM; promotion remains human-review gated.
// pinned bitstream_write_transition: contract_sha256=c0efd335edd62da9ceb5e33d6b34dd35dbca95bcd154cbf3012d5198f74a352e source_body_sha256=4a8b1ea3dad69b2ecc7ea373b037fb3515d4d2485c324c8ae76f224ff9b67ad6
// pinned fifo_read_transition: contract_sha256=51dfb43262052647eaf08bb1a41ee7aeaed7a7578afccb6756390f97b8c62bb7 source_body_sha256=1a4bee3492d25ed63f4b17d10f20e630cb9ada3eac067e1970c9a3f10fae7e29
// pinned fifo_write_transition: contract_sha256=b0bbe172207984f831920abba4df0e5e20e3ede82846cfbc6d835e18e5f272c6 source_body_sha256=175127423ef1e2b5b2c8f62dd77c08283e4594e84c693fcb93536bb9ab918e20
module process_group_encode_fsm #(
    parameter integer MAX_SSPS = 4,
    parameter integer FIFO_ADDR_W = 16,
    parameter integer FRAME_ADDR_W = 32,
    parameter integer MAX_SE_SIZE = 68
) (
    input logic clk,
    input logic rst_n,
    input logic start,
    input logic is_encoder,
    input logic [2:0] num_ssps,
    input logic [6:0] mux_word_size,
    input logic [6:0] max_se_size[0:3],
    input logic [31:0] frame_capacity_bits,
    output logic busy,
    output logic done,
    output logic illegal_domain,
    output logic fifo_underflow,
    output logic fifo_overflow,
    output logic frame_overflow,
    output logic se_size_overflow,
    input logic [31:0] post_mux_num_bits_in,
    output logic [31:0] post_mux_num_bits_out,
    input logic [31:0] enc_balance_size_bits_in[0:3],
    output logic [31:0] enc_balance_size_bits_out[0:3],
    input logic [31:0] enc_balance_fullness_in[0:3],
    output logic [31:0] enc_balance_fullness_out[0:3],
    input logic [31:0] enc_balance_read_ptr_in[0:3],
    output logic [31:0] enc_balance_read_ptr_out[0:3],
    input logic [31:0] enc_balance_write_ptr_in[0:3],
    output logic [31:0] enc_balance_write_ptr_out[0:3],
    input logic [31:0] enc_balance_max_fullness_in[0:3],
    output logic [31:0] enc_balance_max_fullness_out[0:3],
    input logic [31:0] enc_balance_byte_ctr_in[0:3],
    output logic [31:0] enc_balance_byte_ctr_out[0:3],
    output logic [3:0] enc_balance_mem_read_req,
    output logic [15:0] enc_balance_mem_read_addr[0:3],
    input logic [3:0] enc_balance_mem_read_valid,
    input logic [7:0] enc_balance_mem_read_data[0:3],
    output logic [3:0] enc_balance_mem_write_req,
    output logic [15:0] enc_balance_mem_write_addr[0:3],
    input logic [3:0] enc_balance_mem_write_ready,
    output logic [7:0] enc_balance_mem_write_data[0:3],
    output logic [7:0] enc_balance_mem_write_bit_mask[0:3],
    input logic [31:0] shifter_size_bits_in[0:3],
    output logic [31:0] shifter_size_bits_out[0:3],
    input logic [31:0] shifter_fullness_in[0:3],
    output logic [31:0] shifter_fullness_out[0:3],
    input logic [31:0] shifter_read_ptr_in[0:3],
    output logic [31:0] shifter_read_ptr_out[0:3],
    input logic [31:0] shifter_write_ptr_in[0:3],
    output logic [31:0] shifter_write_ptr_out[0:3],
    input logic [31:0] shifter_max_fullness_in[0:3],
    output logic [31:0] shifter_max_fullness_out[0:3],
    input logic [31:0] shifter_byte_ctr_in[0:3],
    output logic [31:0] shifter_byte_ctr_out[0:3],
    output logic [3:0] shifter_mem_read_req,
    output logic [15:0] shifter_mem_read_addr[0:3],
    input logic [3:0] shifter_mem_read_valid,
    input logic [7:0] shifter_mem_read_data[0:3],
    output logic [3:0] shifter_mem_write_req,
    output logic [15:0] shifter_mem_write_addr[0:3],
    input logic [3:0] shifter_mem_write_ready,
    output logic [7:0] shifter_mem_write_data[0:3],
    output logic [7:0] shifter_mem_write_bit_mask[0:3],
    input logic [31:0] se_size_size_bits_in[0:3],
    output logic [31:0] se_size_size_bits_out[0:3],
    input logic [31:0] se_size_fullness_in[0:3],
    output logic [31:0] se_size_fullness_out[0:3],
    input logic [31:0] se_size_read_ptr_in[0:3],
    output logic [31:0] se_size_read_ptr_out[0:3],
    input logic [31:0] se_size_write_ptr_in[0:3],
    output logic [31:0] se_size_write_ptr_out[0:3],
    input logic [31:0] se_size_max_fullness_in[0:3],
    output logic [31:0] se_size_max_fullness_out[0:3],
    input logic [31:0] se_size_byte_ctr_in[0:3],
    output logic [31:0] se_size_byte_ctr_out[0:3],
    output logic [3:0] se_size_mem_read_req,
    output logic [15:0] se_size_mem_read_addr[0:3],
    input logic [3:0] se_size_mem_read_valid,
    input logic [7:0] se_size_mem_read_data[0:3],
    output logic [3:0] se_size_mem_write_req,
    output logic [15:0] se_size_mem_write_addr[0:3],
    input logic [3:0] se_size_mem_write_ready,
    output logic [7:0] se_size_mem_write_data[0:3],
    output logic [7:0] se_size_mem_write_bit_mask[0:3],
    output logic frame_mem_write_req,
    output logic [31:0] frame_mem_write_addr,
    input logic frame_mem_write_ready,
    output logic [7:0] frame_mem_write_data,
    output logic [7:0] frame_mem_write_bit_mask
);

  localparam integer ST_IDLE = 0;
  localparam integer ST_CHECK_SSP = 1;
  localparam integer ST_PREP_ENC_BIT = 2;
  localparam integer ST_ENC_READ = 3;
  localparam integer ST_FRAME_WRITE = 4;
  localparam integer ST_PREP_SHIFTER_WRITE = 5;
  localparam integer ST_SHIFTER_WRITE = 6;
  localparam integer ST_PREP_SE_SIZE = 7;
  localparam integer ST_SE_SIZE_READ = 8;
  localparam integer ST_PREP_SHIFTER_DISCARD = 9;
  localparam integer ST_SHIFTER_DISCARD = 10;
  localparam integer ST_DONE = 11;
  localparam integer ST_ERROR = 12;

  logic [3:0] state_r;
  logic [31:0] enc_balance_size_bits_r [0:3];
  logic [31:0] enc_balance_fullness_r [0:3];
  logic [31:0] enc_balance_read_ptr_r [0:3];
  logic [31:0] enc_balance_write_ptr_r [0:3];
  logic [31:0] enc_balance_max_fullness_r [0:3];
  logic [31:0] enc_balance_byte_ctr_r [0:3];
  logic [31:0] shifter_size_bits_r [0:3];
  logic [31:0] shifter_fullness_r [0:3];
  logic [31:0] shifter_read_ptr_r [0:3];
  logic [31:0] shifter_write_ptr_r [0:3];
  logic [31:0] shifter_max_fullness_r [0:3];
  logic [31:0] shifter_byte_ctr_r [0:3];
  logic [31:0] se_size_size_bits_r [0:3];
  logic [31:0] se_size_fullness_r [0:3];
  logic [31:0] se_size_read_ptr_r [0:3];
  logic [31:0] se_size_write_ptr_r [0:3];
  logic [31:0] se_size_max_fullness_r [0:3];
  logic [31:0] se_size_byte_ctr_r [0:3];
  logic [6:0] max_se_size_r [0:3];
  logic [31:0] frame_capacity_bits_r;
  logic [31:0] post_mux_num_bits_r;
  logic [2:0] ssp_index_r;
  logic [3:0] mux_index_r;
  logic [3:0] enc_bits_total_r;
  logic [3:0] bits_remaining_r;
  logic [7:0] enc_accum_r;
  logic [7:0] mux_byte_r;
  logic [3:0] frame_bit_index_r;
  logic [3:0] shifter_bit_index_r;
  logic [7:0] shifter_bit_data_r;
  logic [3:0] se_bits_remaining_r;
  logic [7:0] se_accum_r;
  logic [7:0] se_size_value_r;
  logic [7:0] discard_remaining_r;
  logic input_legal;
  integer reset_i;

  genvar g;
  generate
    for (g = 0; g < MAX_SSPS; g++) begin : gen_scalar_outputs
      assign enc_balance_size_bits_out[g] = enc_balance_size_bits_r[g];
      assign enc_balance_fullness_out[g] = enc_balance_fullness_r[g];
      assign enc_balance_read_ptr_out[g] = enc_balance_read_ptr_r[g];
      assign enc_balance_write_ptr_out[g] = enc_balance_write_ptr_r[g];
      assign enc_balance_max_fullness_out[g] = enc_balance_max_fullness_r[g];
      assign enc_balance_byte_ctr_out[g] = enc_balance_byte_ctr_r[g];
      assign shifter_size_bits_out[g] = shifter_size_bits_r[g];
      assign shifter_fullness_out[g] = shifter_fullness_r[g];
      assign shifter_read_ptr_out[g] = shifter_read_ptr_r[g];
      assign shifter_write_ptr_out[g] = shifter_write_ptr_r[g];
      assign shifter_max_fullness_out[g] = shifter_max_fullness_r[g];
      assign shifter_byte_ctr_out[g] = shifter_byte_ctr_r[g];
      assign se_size_size_bits_out[g] = se_size_size_bits_r[g];
      assign se_size_fullness_out[g] = se_size_fullness_r[g];
      assign se_size_read_ptr_out[g] = se_size_read_ptr_r[g];
      assign se_size_write_ptr_out[g] = se_size_write_ptr_r[g];
      assign se_size_max_fullness_out[g] = se_size_max_fullness_r[g];
      assign se_size_byte_ctr_out[g] = se_size_byte_ctr_r[g];
    end
  endgenerate
  assign post_mux_num_bits_out = post_mux_num_bits_r;

  function automatic [31:0] advance_ptr;
    input [31:0] ptr;
    input [31:0] size_bits;
    begin
      if ((size_bits != 0) && ((ptr + 32'd1) >= size_bits))
        advance_ptr = 32'd0;
      else
        advance_ptr = ptr + 32'd1;
    end
  endfunction

  function automatic [7:0] one_hot_bit;
    input [2:0] bit_position;
    begin
      one_hot_bit = (8'h01 << bit_position);
    end
  endfunction

  always_comb begin
    input_legal = 1'b1;
    if (is_encoder !== 1'b1)
      input_legal = 1'b0;
    if ((num_ssps < 3) || (num_ssps > MAX_SSPS))
      input_legal = 1'b0;
    if ((mux_word_size != 7'd48) && (mux_word_size != 7'd64))
      input_legal = 1'b0;
    if (post_mux_num_bits_in > frame_capacity_bits)
      input_legal = 1'b0;
    for (integer k = 0; k < MAX_SSPS; k = k + 1) begin
      if (k < num_ssps) begin
        if ((enc_balance_size_bits_in[k] == 0) ||
            ((enc_balance_size_bits_in[k] % 8) != 0) ||
            (enc_balance_fullness_in[k] > enc_balance_size_bits_in[k]) ||
            (enc_balance_read_ptr_in[k] >= enc_balance_size_bits_in[k]) ||
            (enc_balance_write_ptr_in[k] >= enc_balance_size_bits_in[k]) ||
            (enc_balance_max_fullness_in[k] > enc_balance_size_bits_in[k]))
          input_legal = 1'b0;
        if ((shifter_size_bits_in[k] == 0) ||
            ((shifter_size_bits_in[k] % 8) != 0) ||
            (shifter_fullness_in[k] > shifter_size_bits_in[k]) ||
            (shifter_read_ptr_in[k] >= shifter_size_bits_in[k]) ||
            (shifter_write_ptr_in[k] >= shifter_size_bits_in[k]) ||
            (shifter_max_fullness_in[k] > shifter_size_bits_in[k]))
          input_legal = 1'b0;
        if ((se_size_size_bits_in[k] == 0) ||
            ((se_size_size_bits_in[k] % 8) != 0) ||
            (se_size_fullness_in[k] > se_size_size_bits_in[k]) ||
            (se_size_read_ptr_in[k] >= se_size_size_bits_in[k]) ||
            (se_size_write_ptr_in[k] >= se_size_size_bits_in[k]) ||
            (se_size_max_fullness_in[k] > se_size_size_bits_in[k]))
          input_legal = 1'b0;
        if ((max_se_size[k] == 0) || (max_se_size[k] > MAX_SE_SIZE))
          input_legal = 1'b0;
      end
    end
  end

  always_comb begin
    enc_balance_mem_read_req = 4'b0;
    enc_balance_mem_read_addr = '{default:'0};
    enc_balance_mem_write_req = 4'b0;
    enc_balance_mem_write_addr = '{default:'0};
    enc_balance_mem_write_data = '{default:'0};
    enc_balance_mem_write_bit_mask = '{default:'0};
    shifter_mem_read_req = 4'b0;
    shifter_mem_read_addr = '{default:'0};
    shifter_mem_write_req = 4'b0;
    shifter_mem_write_addr = '{default:'0};
    shifter_mem_write_data = '{default:'0};
    shifter_mem_write_bit_mask = '{default:'0};
    se_size_mem_read_req = 4'b0;
    se_size_mem_read_addr = '{default:'0};
    se_size_mem_write_req = 4'b0;
    se_size_mem_write_addr = '{default:'0};
    se_size_mem_write_data = '{default:'0};
    se_size_mem_write_bit_mask = '{default:'0};
    frame_mem_write_req = 1'b0;
    frame_mem_write_addr = '0;
    frame_mem_write_data = 8'h00;
    frame_mem_write_bit_mask = 8'h00;

    if (busy) begin
      if (state_r == ST_ENC_READ) begin
        enc_balance_mem_read_req[ssp_index_r] = 1'b1;
        enc_balance_mem_read_addr[ssp_index_r] =
            enc_balance_read_ptr_r[ssp_index_r] >> 3;
      end
      else if (state_r == ST_SE_SIZE_READ) begin
        se_size_mem_read_req[ssp_index_r] = 1'b1;
        se_size_mem_read_addr[ssp_index_r] =
            se_size_read_ptr_r[ssp_index_r] >> 3;
      end
      else if (state_r == ST_SHIFTER_DISCARD) begin
        shifter_mem_read_req[ssp_index_r] = 1'b1;
        shifter_mem_read_addr[ssp_index_r] =
            shifter_read_ptr_r[ssp_index_r] >> 3;
      end
      else if (state_r == ST_SHIFTER_WRITE) begin
        shifter_mem_write_req[ssp_index_r] = 1'b1;
        shifter_mem_write_addr[ssp_index_r] =
            shifter_write_ptr_r[ssp_index_r] >> 3;
        shifter_mem_write_bit_mask[ssp_index_r] =
            one_hot_bit(3'd7 - shifter_write_ptr_r[ssp_index_r][2:0]);
        shifter_mem_write_data[ssp_index_r] =
            shifter_bit_data_r[7 - shifter_bit_index_r]
            ? one_hot_bit(3'd7 - shifter_write_ptr_r[ssp_index_r][2:0])
            : 8'h00;
      end
      else if (state_r == ST_FRAME_WRITE) begin
        frame_mem_write_req = 1'b1;
        frame_mem_write_addr = post_mux_num_bits_r >> 3;
        frame_mem_write_bit_mask =
            ((post_mux_num_bits_r[2:0] == 0)
                ? 8'hff
                : one_hot_bit(3'd7 - post_mux_num_bits_r[2:0]));
        frame_mem_write_data =
            mux_byte_r[7 - frame_bit_index_r]
                ? one_hot_bit(3'd7 - post_mux_num_bits_r[2:0])
                : 8'h00;
      end
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state_r <= ST_IDLE;
      busy <= 1'b0;
      done <= 1'b0;
      illegal_domain <= 1'b0;
      fifo_underflow <= 1'b0;
      fifo_overflow <= 1'b0;
      frame_overflow <= 1'b0;
      se_size_overflow <= 1'b0;
      post_mux_num_bits_r <= 32'd0;
      frame_capacity_bits_r <= 32'd0;
      ssp_index_r <= 3'd0;
      mux_index_r <= 4'd0;
      enc_bits_total_r <= 4'd0;
      bits_remaining_r <= 4'd0;
      enc_accum_r <= 8'd0;
      mux_byte_r <= 8'd0;
      frame_bit_index_r <= 4'd0;
      shifter_bit_index_r <= 4'd0;
      shifter_bit_data_r <= 8'd0;
      se_bits_remaining_r <= 4'd0;
      se_accum_r <= 8'd0;
      se_size_value_r <= 8'd0;
      discard_remaining_r <= 8'd0;
      for (reset_i = 0; reset_i < MAX_SSPS; reset_i = reset_i + 1) begin
        enc_balance_size_bits_r[reset_i] <= 32'd0;
        enc_balance_fullness_r[reset_i] <= 32'd0;
        enc_balance_read_ptr_r[reset_i] <= 32'd0;
        enc_balance_write_ptr_r[reset_i] <= 32'd0;
        enc_balance_max_fullness_r[reset_i] <= 32'd0;
        enc_balance_byte_ctr_r[reset_i] <= 32'd0;
        shifter_size_bits_r[reset_i] <= 32'd0;
        shifter_fullness_r[reset_i] <= 32'd0;
        shifter_read_ptr_r[reset_i] <= 32'd0;
        shifter_write_ptr_r[reset_i] <= 32'd0;
        shifter_max_fullness_r[reset_i] <= 32'd0;
        shifter_byte_ctr_r[reset_i] <= 32'd0;
        se_size_size_bits_r[reset_i] <= 32'd0;
        se_size_fullness_r[reset_i] <= 32'd0;
        se_size_read_ptr_r[reset_i] <= 32'd0;
        se_size_write_ptr_r[reset_i] <= 32'd0;
        se_size_max_fullness_r[reset_i] <= 32'd0;
        se_size_byte_ctr_r[reset_i] <= 32'd0;
        max_se_size_r[reset_i] <= 7'd0;
      end
    end
    else begin
      done <= 1'b0;
      case (state_r)
        ST_IDLE: begin
          busy <= 1'b0;
          if (start) begin
            illegal_domain <= 1'b0;
            fifo_underflow <= 1'b0;
            fifo_overflow <= 1'b0;
            frame_overflow <= 1'b0;
            se_size_overflow <= 1'b0;
            post_mux_num_bits_r <= post_mux_num_bits_in;
            frame_capacity_bits_r <= frame_capacity_bits;
            ssp_index_r <= 3'd0;
            mux_index_r <= 4'd0;
            for (reset_i = 0; reset_i < MAX_SSPS; reset_i = reset_i + 1) begin
              enc_balance_size_bits_r[reset_i] <= enc_balance_size_bits_in[reset_i];
              enc_balance_fullness_r[reset_i] <= enc_balance_fullness_in[reset_i];
              enc_balance_read_ptr_r[reset_i] <= enc_balance_read_ptr_in[reset_i];
              enc_balance_write_ptr_r[reset_i] <= enc_balance_write_ptr_in[reset_i];
              enc_balance_max_fullness_r[reset_i] <= enc_balance_max_fullness_in[reset_i];
              enc_balance_byte_ctr_r[reset_i] <= enc_balance_byte_ctr_in[reset_i];
              shifter_size_bits_r[reset_i] <= shifter_size_bits_in[reset_i];
              shifter_fullness_r[reset_i] <= shifter_fullness_in[reset_i];
              shifter_read_ptr_r[reset_i] <= shifter_read_ptr_in[reset_i];
              shifter_write_ptr_r[reset_i] <= shifter_write_ptr_in[reset_i];
              shifter_max_fullness_r[reset_i] <= shifter_max_fullness_in[reset_i];
              shifter_byte_ctr_r[reset_i] <= shifter_byte_ctr_in[reset_i];
              se_size_size_bits_r[reset_i] <= se_size_size_bits_in[reset_i];
              se_size_fullness_r[reset_i] <= se_size_fullness_in[reset_i];
              se_size_read_ptr_r[reset_i] <= se_size_read_ptr_in[reset_i];
              se_size_write_ptr_r[reset_i] <= se_size_write_ptr_in[reset_i];
              se_size_max_fullness_r[reset_i] <= se_size_max_fullness_in[reset_i];
              se_size_byte_ctr_r[reset_i] <= se_size_byte_ctr_in[reset_i];
              max_se_size_r[reset_i] <= max_se_size[reset_i];
            end
            if (!input_legal) begin
              illegal_domain <= 1'b1;
              state_r <= ST_ERROR;
              busy <= 1'b0;
            end
            else begin
              state_r <= ST_CHECK_SSP;
              busy <= 1'b1;
            end
          end
        end

        ST_CHECK_SSP: begin
          if (ssp_index_r >= num_ssps) begin
            state_r <= ST_DONE;
          end
          else if (shifter_fullness_r[ssp_index_r] < max_se_size_r[ssp_index_r]) begin
            mux_index_r <= 4'd0;
            state_r <= ST_PREP_ENC_BIT;
          end
          else begin
            state_r <= ST_PREP_SE_SIZE;
          end
        end

        ST_PREP_ENC_BIT: begin
          if (enc_balance_fullness_r[ssp_index_r] >= 8) begin
            enc_bits_total_r <= 4'd8;
          end
          else begin
            enc_bits_total_r <= enc_balance_fullness_r[ssp_index_r][3:0];
          end
          enc_accum_r <= 8'd0;
          bits_remaining_r <=
              (enc_balance_fullness_r[ssp_index_r] >= 8)
                  ? 4'd8
                  : enc_balance_fullness_r[ssp_index_r][3:0];
          if (enc_balance_fullness_r[ssp_index_r] == 0) begin
            mux_byte_r <= 8'd0;
            frame_bit_index_r <= 4'd0;
            state_r <= ST_FRAME_WRITE;
          end
          else if (enc_balance_fullness_r[ssp_index_r] > enc_balance_size_bits_r[ssp_index_r]) begin
            fifo_underflow <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            state_r <= ST_ENC_READ;
          end
        end

        ST_ENC_READ: begin
          if (enc_balance_mem_read_valid[ssp_index_r]) begin
            enc_accum_r <= {
                enc_accum_r[6:0],
                enc_balance_mem_read_data[ssp_index_r][7 - enc_balance_read_ptr_r[ssp_index_r][2:0]]
            };
            enc_balance_fullness_r[ssp_index_r] <=
                enc_balance_fullness_r[ssp_index_r] - 32'd1;
            enc_balance_read_ptr_r[ssp_index_r] <= advance_ptr(
                enc_balance_read_ptr_r[ssp_index_r],
                enc_balance_size_bits_r[ssp_index_r]
            );
            if (bits_remaining_r == 1) begin
              if (enc_bits_total_r == 8)
                mux_byte_r <= {
                    enc_accum_r[6:0],
                    enc_balance_mem_read_data[ssp_index_r][7 - enc_balance_read_ptr_r[ssp_index_r][2:0]]
                };
              else
                mux_byte_r <= (
                    {
                        enc_accum_r[6:0],
                        enc_balance_mem_read_data[ssp_index_r][7 - enc_balance_read_ptr_r[ssp_index_r][2:0]]
                    } << (8 - enc_bits_total_r)
                );
              frame_bit_index_r <= 4'd0;
              state_r <= ST_FRAME_WRITE;
            end
            else begin
              bits_remaining_r <= bits_remaining_r - 4'd1;
            end
          end
        end

        ST_FRAME_WRITE: begin
          if ((post_mux_num_bits_r + 32'd8) > frame_capacity_bits_r) begin
            frame_overflow <= 1'b1;
            state_r <= ST_ERROR;
          end
          else if (frame_mem_write_ready) begin
            post_mux_num_bits_r <= post_mux_num_bits_r + 32'd1;
            if (frame_bit_index_r == 7) begin
              shifter_bit_data_r <= mux_byte_r;
              shifter_bit_index_r <= 4'd0;
              state_r <= ST_PREP_SHIFTER_WRITE;
            end
            else begin
              frame_bit_index_r <= frame_bit_index_r + 4'd1;
            end
          end
        end

        ST_PREP_SHIFTER_WRITE: begin
          if ((shifter_fullness_r[ssp_index_r] + 32'd8) >
              shifter_size_bits_r[ssp_index_r]) begin
            fifo_overflow <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            shifter_fullness_r[ssp_index_r] <=
                shifter_fullness_r[ssp_index_r] + 32'd8;
            if ((shifter_fullness_r[ssp_index_r] + 32'd8) >
                shifter_max_fullness_r[ssp_index_r])
              shifter_max_fullness_r[ssp_index_r] <=
                  shifter_fullness_r[ssp_index_r] + 32'd8;
            state_r <= ST_SHIFTER_WRITE;
          end
        end

        ST_SHIFTER_WRITE: begin
          if (shifter_mem_write_ready[ssp_index_r]) begin
            shifter_write_ptr_r[ssp_index_r] <= advance_ptr(
                shifter_write_ptr_r[ssp_index_r],
                shifter_size_bits_r[ssp_index_r]
            );
            if (shifter_bit_index_r == 7) begin
              if (mux_index_r + 4'd1 < (mux_word_size / 8)) begin
                mux_index_r <= mux_index_r + 4'd1;
                state_r <= ST_PREP_ENC_BIT;
              end
              else begin
                state_r <= ST_PREP_SE_SIZE;
              end
            end
            else begin
              shifter_bit_index_r <= shifter_bit_index_r + 4'd1;
            end
          end
        end

        ST_PREP_SE_SIZE: begin
          if (se_size_fullness_r[ssp_index_r] < 8) begin
            fifo_underflow <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            se_bits_remaining_r <= 4'd8;
            se_accum_r <= 8'd0;
            state_r <= ST_SE_SIZE_READ;
          end
        end

        ST_SE_SIZE_READ: begin
          if (se_size_mem_read_valid[ssp_index_r]) begin
            se_accum_r <= {
                se_accum_r[6:0],
                se_size_mem_read_data[ssp_index_r][7 - se_size_read_ptr_r[ssp_index_r][2:0]]
            };
            se_size_fullness_r[ssp_index_r] <=
                se_size_fullness_r[ssp_index_r] - 32'd1;
            se_size_read_ptr_r[ssp_index_r] <= advance_ptr(
                se_size_read_ptr_r[ssp_index_r],
                se_size_size_bits_r[ssp_index_r]
            );
            if (se_bits_remaining_r == 1) begin
              se_size_value_r <= {
                  se_accum_r[6:0],
                  se_size_mem_read_data[ssp_index_r][7 - se_size_read_ptr_r[ssp_index_r][2:0]]
              };
              state_r <= ST_PREP_SHIFTER_DISCARD;
            end
            else begin
              se_bits_remaining_r <= se_bits_remaining_r - 4'd1;
            end
          end
        end

        ST_PREP_SHIFTER_DISCARD: begin
          if (se_size_value_r > MAX_SE_SIZE) begin
            se_size_overflow <= 1'b1;
            illegal_domain <= 1'b1;
            state_r <= ST_ERROR;
          end
          else if (shifter_fullness_r[ssp_index_r] < se_size_value_r) begin
            fifo_underflow <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            discard_remaining_r <= se_size_value_r;
            if (se_size_value_r == 0) begin
              if (ssp_index_r + 3'd1 < num_ssps)
                ssp_index_r <= ssp_index_r + 3'd1;
              else
                ssp_index_r <= num_ssps;
              state_r <= ST_CHECK_SSP;
            end
            else begin
              state_r <= ST_SHIFTER_DISCARD;
            end
          end
        end

        ST_SHIFTER_DISCARD: begin
          if (shifter_mem_read_valid[ssp_index_r]) begin
            shifter_fullness_r[ssp_index_r] <=
                shifter_fullness_r[ssp_index_r] - 32'd1;
            shifter_read_ptr_r[ssp_index_r] <= advance_ptr(
                shifter_read_ptr_r[ssp_index_r],
                shifter_size_bits_r[ssp_index_r]
            );
            if (discard_remaining_r == 1) begin
              if (ssp_index_r + 3'd1 < num_ssps)
                ssp_index_r <= ssp_index_r + 3'd1;
              else
                ssp_index_r <= num_ssps;
              state_r <= ST_CHECK_SSP;
            end
            else begin
              discard_remaining_r <= discard_remaining_r - 8'd1;
            end
          end
        end

        ST_DONE: begin
          busy <= 1'b0;
          done <= 1'b1;
          state_r <= ST_IDLE;
        end

        ST_ERROR: begin
          busy <= 1'b0;
          done <= 1'b1;
          state_r <= ST_IDLE;
        end

        default: begin
          illegal_domain <= 1'b1;
          busy <= 1'b0;
          state_r <= ST_ERROR;
        end
      endcase
    end
  end

endmodule
