// Generated by tools/generate_vlc_group_encode.py
// Encoder-only bounded sequential parent; child RTL is externally composed.
// No C source, promotion state, or child module is modified or absorbed here.
// pinned process_group: contract_sha256=028e379da74e8df5a2313a856d671d0c9d280f6c756d11b4c8234ae9cec4cb57 module_sha256=5aeacbb6c1e46b5ebbe2767f523bf9f7ed91053dbad2d321e442a49828c84e6e source_body_sha256=30b4e2cf73b2bcecf90d68143cbca203888622546f92b000193ceda40d4498fb source_file_sha256=ab549255599fbdf1f69dd9fa8013ed39c044c3b8f591b187e2e056a5f1f5ab50
// pinned vlc_unit: contract_sha256=37f4a90480d1c6e05997c849f9e89b8646953383f859b5ea3e10edb86eb9b6d6 module_sha256=a602e976fd06e9481b2faa8bcadf8303025a690ffe574aac076b1869da799ded source_body_sha256=68f11a3cc9c8b65c280e2cb29df2988529a556887253e956caa206ab41ac73f4 source_file_sha256=0adcf9732bdbe11281982dafa134ee858432097d559f11397124449615a2dddf
module vlc_group_encode_fsm #(
    parameter integer MAX_SSPS = 4,
    parameter integer MAX_UNITS = 4,
    parameter integer MAX_SE_SIZE = 68,
    parameter integer MAX_CYCLES = 4096
) (
    input logic clk,
    input logic rst_n,
    input logic start,
    input logic is_encoder,
    input logic [2:0] units_per_group,
    input logic [2:0] num_ssps,
    input logic [6:0] mux_word_size,
    input logic signed [31:0] bits_per_pixel,
    input logic signed [5:0] bits_per_component,
    input logic signed [31:0] chunk_size,
    input logic signed [31:0] initial_xmit_delay,
    input logic vbr_enable,
    input logic signed [31:0] rcb_bits,
    input logic [31:0] frame_capacity_bits,
    input logic [6:0] max_se_size[0:3],
    output logic busy,
    output logic done,
    output logic domain_valid,
    output logic illegal_domain,
    output logic fatal_error,
    output logic bound_violation,
    output logic child_error,
    output logic fifo_underflow,
    output logic fifo_overflow,
    output logic se_size_overflow,
    output logic buffer_overflow,
    input logic [31:0] post_mux_num_bits_in,
    output logic [31:0] post_mux_num_bits_out,
    input logic signed [31:0] num_bits_in,
    output logic signed [31:0] num_bits_out,
    input logic signed [31:0] buffer_fullness_in,
    output logic signed [31:0] buffer_fullness_out,
    input logic signed [31:0] num_bits_chunk_in,
    output logic signed [31:0] num_bits_chunk_out,
    input logic signed [31:0] pixels_in_group_in,
    output logic signed [31:0] pixels_in_group_out,
    input logic signed [31:0] slice_width_in,
    output logic signed [31:0] slice_width_out,
    input logic signed [31:0] pixel_count_in,
    output logic signed [31:0] pixel_count_out,
    input logic signed [31:0] group_count_in,
    output logic signed [31:0] group_count_out,
    input logic signed [31:0] primary_qp_in,
    output logic signed [31:0] primary_qp_out,
    input logic signed [31:0] prev_primary_qp_in,
    output logic signed [31:0] prev_primary_qp_out,
    input logic signed [31:0] prev_num_bits_in,
    output logic signed [31:0] prev_num_bits_out,
    input logic signed [31:0] coded_group_size_in,
    output logic signed [31:0] coded_group_size_out,
    input logic signed [31:0] group_count_line_in,
    output logic signed [31:0] group_count_line_out,
    input logic signed [31:0] force_mpp_in,
    output logic signed [31:0] force_mpp_out,
    input logic signed [31:0] midpoint_selected_in[0:3],
    output logic signed [31:0] midpoint_selected_out[0:3],
    input logic signed [31:0] quantized_residual_in[0:3][0:2],
    output logic signed [31:0] quantized_residual_out[0:3][0:2],
    input logic signed [31:0] quantized_residual_mid_in[0:3][0:2],
    output logic signed [31:0] quantized_residual_mid_out[0:3][0:2],
    input logic [31:0] enc_balance_size_bits_in[0:3],
    output logic [31:0] enc_balance_size_bits_out[0:3],
    input logic [31:0] enc_balance_fullness_in[0:3],
    output logic [31:0] enc_balance_fullness_out[0:3],
    input logic [31:0] enc_balance_read_ptr_in[0:3],
    output logic [31:0] enc_balance_read_ptr_out[0:3],
    input logic [31:0] enc_balance_write_ptr_in[0:3],
    output logic [31:0] enc_balance_write_ptr_out[0:3],
    input logic [31:0] enc_balance_max_fullness_in[0:3],
    output logic [31:0] enc_balance_max_fullness_out[0:3],
    input logic [31:0] enc_balance_byte_ctr_in[0:3],
    output logic [31:0] enc_balance_byte_ctr_out[0:3],
    output logic [3:0] enc_balance_mem_read_req,
    output logic [15:0] enc_balance_mem_read_addr[0:3],
    input logic [3:0] enc_balance_mem_read_valid,
    input logic [7:0] enc_balance_mem_read_data[0:3],
    output logic [3:0] enc_balance_mem_write_req,
    output logic [15:0] enc_balance_mem_write_addr[0:3],
    input logic [3:0] enc_balance_mem_write_ready,
    output logic [7:0] enc_balance_mem_write_data[0:3],
    output logic [7:0] enc_balance_mem_write_bit_mask[0:3],
    input logic [31:0] shifter_size_bits_in[0:3],
    output logic [31:0] shifter_size_bits_out[0:3],
    input logic [31:0] shifter_fullness_in[0:3],
    output logic [31:0] shifter_fullness_out[0:3],
    input logic [31:0] shifter_read_ptr_in[0:3],
    output logic [31:0] shifter_read_ptr_out[0:3],
    input logic [31:0] shifter_write_ptr_in[0:3],
    output logic [31:0] shifter_write_ptr_out[0:3],
    input logic [31:0] shifter_max_fullness_in[0:3],
    output logic [31:0] shifter_max_fullness_out[0:3],
    input logic [31:0] shifter_byte_ctr_in[0:3],
    output logic [31:0] shifter_byte_ctr_out[0:3],
    output logic [3:0] shifter_mem_read_req,
    output logic [15:0] shifter_mem_read_addr[0:3],
    input logic [3:0] shifter_mem_read_valid,
    input logic [7:0] shifter_mem_read_data[0:3],
    output logic [3:0] shifter_mem_write_req,
    output logic [15:0] shifter_mem_write_addr[0:3],
    input logic [3:0] shifter_mem_write_ready,
    output logic [7:0] shifter_mem_write_data[0:3],
    output logic [7:0] shifter_mem_write_bit_mask[0:3],
    input logic [31:0] se_size_size_bits_in[0:3],
    output logic [31:0] se_size_size_bits_out[0:3],
    input logic [31:0] se_size_fullness_in[0:3],
    output logic [31:0] se_size_fullness_out[0:3],
    input logic [31:0] se_size_read_ptr_in[0:3],
    output logic [31:0] se_size_read_ptr_out[0:3],
    input logic [31:0] se_size_write_ptr_in[0:3],
    output logic [31:0] se_size_write_ptr_out[0:3],
    input logic [31:0] se_size_max_fullness_in[0:3],
    output logic [31:0] se_size_max_fullness_out[0:3],
    input logic [31:0] se_size_byte_ctr_in[0:3],
    output logic [31:0] se_size_byte_ctr_out[0:3],
    output logic [3:0] se_size_mem_read_req,
    output logic [15:0] se_size_mem_read_addr[0:3],
    input logic [3:0] se_size_mem_read_valid,
    input logic [7:0] se_size_mem_read_data[0:3],
    output logic [3:0] se_size_mem_write_req,
    output logic [15:0] se_size_mem_write_addr[0:3],
    input logic [3:0] se_size_mem_write_ready,
    output logic [7:0] se_size_mem_write_data[0:3],
    output logic [7:0] se_size_mem_write_bit_mask[0:3],
    output logic vlc_unit_start,
    input logic vlc_unit_ready,
    input logic vlc_unit_done,
    input logic vlc_unit_domain_valid,
    input logic vlc_unit_fatal_error,
    output logic [2:0] vlc_unit_index,
    output logic signed [31:0] vlc_unit_force_p1_ich2,
    output logic signed [31:0] vlc_unit_num_bits_in,
    input logic signed [31:0] vlc_unit_num_bits_out,
    output logic signed [31:0] vlc_unit_primary_qp_in,
    input logic signed [31:0] vlc_unit_primary_qp_out,
    output logic [31:0] vlc_unit_enc_balance_size_bits_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_size_bits_out[0:3],
    output logic [31:0] vlc_unit_enc_balance_fullness_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_fullness_out[0:3],
    output logic [31:0] vlc_unit_enc_balance_read_ptr_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_read_ptr_out[0:3],
    output logic [31:0] vlc_unit_enc_balance_write_ptr_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_write_ptr_out[0:3],
    output logic [31:0] vlc_unit_enc_balance_max_fullness_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_max_fullness_out[0:3],
    output logic [31:0] vlc_unit_enc_balance_byte_ctr_in[0:3],
    input logic [31:0] vlc_unit_enc_balance_byte_ctr_out[0:3],
    output logic [31:0] vlc_unit_shifter_size_bits_in[0:3],
    output logic [31:0] vlc_unit_shifter_fullness_in[0:3],
    output logic [31:0] vlc_unit_shifter_read_ptr_in[0:3],
    output logic [31:0] vlc_unit_shifter_write_ptr_in[0:3],
    output logic [31:0] vlc_unit_shifter_max_fullness_in[0:3],
    output logic [31:0] vlc_unit_shifter_byte_ctr_in[0:3],
    output logic [31:0] vlc_unit_se_size_size_bits_in[0:3],
    output logic [31:0] vlc_unit_se_size_fullness_in[0:3],
    output logic [31:0] vlc_unit_se_size_read_ptr_in[0:3],
    output logic [31:0] vlc_unit_se_size_write_ptr_in[0:3],
    output logic [31:0] vlc_unit_se_size_max_fullness_in[0:3],
    output logic [31:0] vlc_unit_se_size_byte_ctr_in[0:3],
    input logic [3:0] vlc_unit_enc_balance_mem_read_req,
    input logic [15:0] vlc_unit_enc_balance_mem_read_addr[0:3],
    output logic [3:0] vlc_unit_enc_balance_mem_read_valid,
    output logic [7:0] vlc_unit_enc_balance_mem_read_data[0:3],
    input logic [3:0] vlc_unit_enc_balance_mem_write_req,
    input logic [15:0] vlc_unit_enc_balance_mem_write_addr[0:3],
    output logic [3:0] vlc_unit_enc_balance_mem_write_ready,
    input logic [7:0] vlc_unit_enc_balance_mem_write_data[0:3],
    input logic [7:0] vlc_unit_enc_balance_mem_write_bit_mask[0:3],
    input logic [3:0] vlc_unit_shifter_mem_read_req,
    input logic [15:0] vlc_unit_shifter_mem_read_addr[0:3],
    output logic [3:0] vlc_unit_shifter_mem_read_valid,
    output logic [7:0] vlc_unit_shifter_mem_read_data[0:3],
    input logic [3:0] vlc_unit_shifter_mem_write_req,
    input logic [15:0] vlc_unit_shifter_mem_write_addr[0:3],
    output logic [3:0] vlc_unit_shifter_mem_write_ready,
    input logic [7:0] vlc_unit_shifter_mem_write_data[0:3],
    input logic [7:0] vlc_unit_shifter_mem_write_bit_mask[0:3],
    input logic [3:0] vlc_unit_se_size_mem_read_req,
    input logic [15:0] vlc_unit_se_size_mem_read_addr[0:3],
    output logic [3:0] vlc_unit_se_size_mem_read_valid,
    output logic [7:0] vlc_unit_se_size_mem_read_data[0:3],
    input logic [3:0] vlc_unit_se_size_mem_write_req,
    input logic [15:0] vlc_unit_se_size_mem_write_addr[0:3],
    output logic [3:0] vlc_unit_se_size_mem_write_ready,
    input logic [7:0] vlc_unit_se_size_mem_write_data[0:3],
    input logic [7:0] vlc_unit_se_size_mem_write_bit_mask[0:3],
    output logic process_group_start,
    input logic process_group_ready,
    input logic process_group_done,
    input logic process_group_domain_valid,
    input logic process_group_fatal_error,
    output logic process_group_is_encoder,
    output logic [2:0] process_group_num_ssps,
    output logic [6:0] process_group_mux_word_size,
    output logic [31:0] process_group_frame_capacity_bits,
    output logic [31:0] process_group_post_mux_num_bits_in,
    input logic [31:0] process_group_post_mux_num_bits_out,
    output logic [31:0] process_group_enc_balance_size_bits_in[0:3],
    input logic [31:0] process_group_enc_balance_size_bits_out[0:3],
    output logic [31:0] process_group_enc_balance_fullness_in[0:3],
    input logic [31:0] process_group_enc_balance_fullness_out[0:3],
    output logic [31:0] process_group_enc_balance_read_ptr_in[0:3],
    input logic [31:0] process_group_enc_balance_read_ptr_out[0:3],
    output logic [31:0] process_group_enc_balance_write_ptr_in[0:3],
    input logic [31:0] process_group_enc_balance_write_ptr_out[0:3],
    output logic [31:0] process_group_enc_balance_max_fullness_in[0:3],
    input logic [31:0] process_group_enc_balance_max_fullness_out[0:3],
    output logic [31:0] process_group_enc_balance_byte_ctr_in[0:3],
    input logic [31:0] process_group_enc_balance_byte_ctr_out[0:3],
    input logic [3:0] process_group_enc_balance_mem_read_req,
    input logic [15:0] process_group_enc_balance_mem_read_addr[0:3],
    output logic [3:0] process_group_enc_balance_mem_read_valid,
    output logic [7:0] process_group_enc_balance_mem_read_data[0:3],
    input logic [3:0] process_group_enc_balance_mem_write_req,
    input logic [15:0] process_group_enc_balance_mem_write_addr[0:3],
    output logic [3:0] process_group_enc_balance_mem_write_ready,
    input logic [7:0] process_group_enc_balance_mem_write_data[0:3],
    input logic [7:0] process_group_enc_balance_mem_write_bit_mask[0:3],
    output logic [31:0] process_group_shifter_size_bits_in[0:3],
    input logic [31:0] process_group_shifter_size_bits_out[0:3],
    output logic [31:0] process_group_shifter_fullness_in[0:3],
    input logic [31:0] process_group_shifter_fullness_out[0:3],
    output logic [31:0] process_group_shifter_read_ptr_in[0:3],
    input logic [31:0] process_group_shifter_read_ptr_out[0:3],
    output logic [31:0] process_group_shifter_write_ptr_in[0:3],
    input logic [31:0] process_group_shifter_write_ptr_out[0:3],
    output logic [31:0] process_group_shifter_max_fullness_in[0:3],
    input logic [31:0] process_group_shifter_max_fullness_out[0:3],
    output logic [31:0] process_group_shifter_byte_ctr_in[0:3],
    input logic [31:0] process_group_shifter_byte_ctr_out[0:3],
    input logic [3:0] process_group_shifter_mem_read_req,
    input logic [15:0] process_group_shifter_mem_read_addr[0:3],
    output logic [3:0] process_group_shifter_mem_read_valid,
    output logic [7:0] process_group_shifter_mem_read_data[0:3],
    input logic [3:0] process_group_shifter_mem_write_req,
    input logic [15:0] process_group_shifter_mem_write_addr[0:3],
    output logic [3:0] process_group_shifter_mem_write_ready,
    input logic [7:0] process_group_shifter_mem_write_data[0:3],
    input logic [7:0] process_group_shifter_mem_write_bit_mask[0:3],
    output logic [31:0] process_group_se_size_size_bits_in[0:3],
    input logic [31:0] process_group_se_size_size_bits_out[0:3],
    output logic [31:0] process_group_se_size_fullness_in[0:3],
    input logic [31:0] process_group_se_size_fullness_out[0:3],
    output logic [31:0] process_group_se_size_read_ptr_in[0:3],
    input logic [31:0] process_group_se_size_read_ptr_out[0:3],
    output logic [31:0] process_group_se_size_write_ptr_in[0:3],
    input logic [31:0] process_group_se_size_write_ptr_out[0:3],
    output logic [31:0] process_group_se_size_max_fullness_in[0:3],
    input logic [31:0] process_group_se_size_max_fullness_out[0:3],
    output logic [31:0] process_group_se_size_byte_ctr_in[0:3],
    input logic [31:0] process_group_se_size_byte_ctr_out[0:3],
    input logic [3:0] process_group_se_size_mem_read_req,
    input logic [15:0] process_group_se_size_mem_read_addr[0:3],
    output logic [3:0] process_group_se_size_mem_read_valid,
    output logic [7:0] process_group_se_size_mem_read_data[0:3],
    input logic [3:0] process_group_se_size_mem_write_req,
    input logic [15:0] process_group_se_size_mem_write_addr[0:3],
    output logic [3:0] process_group_se_size_mem_write_ready,
    input logic [7:0] process_group_se_size_mem_write_data[0:3],
    input logic [7:0] process_group_se_size_mem_write_bit_mask[0:3],
    input logic process_group_frame_mem_write_req,
    input logic [31:0] process_group_frame_mem_write_addr,
    output logic process_group_frame_mem_write_ready,
    input logic [7:0] process_group_frame_mem_write_data,
    input logic [7:0] process_group_frame_mem_write_bit_mask,
    output logic frame_mem_write_req,
    output logic [31:0] frame_mem_write_addr,
    input logic frame_mem_write_ready,
    output logic [7:0] frame_mem_write_data,
    output logic [7:0] frame_mem_write_bit_mask
);

  localparam integer ST_IDLE = 0;
  localparam integer ST_INIT = 1;
  localparam integer ST_VLC_START = 2;
  localparam integer ST_VLC_WAIT = 3;
  localparam integer ST_SE_PREP = 4;
  localparam integer ST_SE_WRITE = 5;
  localparam integer ST_PROCESS_CHECK = 6;
  localparam integer ST_PROCESS_START = 7;
  localparam integer ST_PROCESS_WAIT = 8;
  localparam integer ST_ACCOUNT = 9;
  localparam integer ST_DONE = 10;
  localparam integer ST_ERROR = 11;
  localparam integer MIN_SSPS = 3;
  localparam integer MIN_UNITS = 3;

  logic [3:0] state_r;
  logic [2:0] unit_index_r;
  logic [2:0] ssp_index_r;
  logic [31:0] cycle_count_r;
  logic [31:0] start_fullness_r [0:MAX_SSPS-1];
  logic [31:0] se_delta_r;
  logic [7:0] se_write_data_r;
  logic signed [31:0] num_bits_r;
  logic signed [31:0] buffer_fullness_r;
  logic signed [31:0] num_bits_chunk_r;
  logic signed [31:0] pixels_in_group_r;
  logic signed [31:0] slice_width_r;
  logic signed [31:0] pixel_count_r;
  logic signed [31:0] group_count_r;
  logic signed [31:0] primary_qp_r;
  logic signed [31:0] prev_primary_qp_r;
  logic signed [31:0] prev_num_bits_r;
  logic signed [31:0] coded_group_size_r;
  logic signed [31:0] group_count_line_r;
  logic signed [31:0] force_mpp_r;
  logic signed [31:0] force_p1_ich2_r;
  logic [31:0] post_mux_num_bits_r;
  logic signed [31:0] midpoint_selected_r [0:MAX_UNITS-1];
  logic domain_valid_r;
  logic illegal_domain_r;
  logic fatal_error_r;
  logic bound_violation_r;
  logic child_error_r;
  logic fifo_underflow_r;
  logic fifo_overflow_r;
  logic se_size_overflow_r;
  logic buffer_overflow_r;
  logic input_legal;
  logic force_mpp_calc;
  logic signed [31:0] active_max_se_size;
  logic [31:0] enc_balance_size_bits_r [0:MAX_SSPS-1];
  logic [31:0] enc_balance_fullness_r [0:MAX_SSPS-1];
  logic [31:0] enc_balance_read_ptr_r [0:MAX_SSPS-1];
  logic [31:0] enc_balance_write_ptr_r [0:MAX_SSPS-1];
  logic [31:0] enc_balance_max_fullness_r [0:MAX_SSPS-1];
  logic [31:0] enc_balance_byte_ctr_r [0:MAX_SSPS-1];
  logic [31:0] shifter_size_bits_r [0:MAX_SSPS-1];
  logic [31:0] shifter_fullness_r [0:MAX_SSPS-1];
  logic [31:0] shifter_read_ptr_r [0:MAX_SSPS-1];
  logic [31:0] shifter_write_ptr_r [0:MAX_SSPS-1];
  logic [31:0] shifter_max_fullness_r [0:MAX_SSPS-1];
  logic [31:0] shifter_byte_ctr_r [0:MAX_SSPS-1];
  logic [31:0] se_size_size_bits_r [0:MAX_SSPS-1];
  logic [31:0] se_size_fullness_r [0:MAX_SSPS-1];
  logic [31:0] se_size_read_ptr_r [0:MAX_SSPS-1];
  logic [31:0] se_size_write_ptr_r [0:MAX_SSPS-1];
  logic [31:0] se_size_max_fullness_r [0:MAX_SSPS-1];
  logic [31:0] se_size_byte_ctr_r [0:MAX_SSPS-1];

  integer reset_i;
  integer k;
  integer max_bits_i;
  integer adjusted_fullness_i;
  integer bug_fix_condition_i;

  assign active_max_se_size =
      ($signed(bits_per_component) * 32'sd4) + 32'sd4;

  always_comb begin
    input_legal = 1'b1;
    if (is_encoder != 1'b1)
      input_legal = 1'b0;
    if ((units_per_group < MIN_UNITS) || (units_per_group > MAX_UNITS))
      input_legal = 1'b0;
    if ((num_ssps < MIN_SSPS) || (num_ssps > MAX_SSPS))
      input_legal = 1'b0;
    if ((mux_word_size != 7'd48) && (mux_word_size != 7'd64))
      input_legal = 1'b0;
    if ((bits_per_component < 8) || (bits_per_component > 16))
      input_legal = 1'b0;
    if ((bits_per_pixel < 0) || (chunk_size <= 0) || (rcb_bits <= 0) ||
        (frame_capacity_bits <= 0))
      input_legal = 1'b0;
    for (k = 0; k < MAX_SSPS; k = k + 1) begin
      if (k < num_ssps) begin
        if ((max_se_size[k] == 0) || (max_se_size[k] > MAX_SE_SIZE))
          input_legal = 1'b0;
        if ((enc_balance_size_bits_in[k] == 0) ||
            ((enc_balance_size_bits_in[k] % 8) != 0) ||
            (enc_balance_fullness_in[k] > enc_balance_size_bits_in[k]) ||
            (enc_balance_read_ptr_in[k] >= enc_balance_size_bits_in[k]) ||
            (enc_balance_write_ptr_in[k] >= enc_balance_size_bits_in[k]) ||
            (enc_balance_max_fullness_in[k] > enc_balance_size_bits_in[k]))
          input_legal = 1'b0;
        if ((shifter_size_bits_in[k] == 0) ||
            ((shifter_size_bits_in[k] % 8) != 0) ||
            (shifter_fullness_in[k] > shifter_size_bits_in[k]) ||
            (shifter_read_ptr_in[k] >= shifter_size_bits_in[k]) ||
            (shifter_write_ptr_in[k] >= shifter_size_bits_in[k]) ||
            (shifter_max_fullness_in[k] > shifter_size_bits_in[k]))
          input_legal = 1'b0;
        if ((se_size_size_bits_in[k] == 0) ||
            ((se_size_size_bits_in[k] % 8) != 0) ||
            (se_size_fullness_in[k] > se_size_size_bits_in[k]) ||
            (se_size_read_ptr_in[k] >= se_size_size_bits_in[k]) ||
            (se_size_write_ptr_in[k] >= se_size_size_bits_in[k]) ||
            (se_size_max_fullness_in[k] > se_size_size_bits_in[k]))
          input_legal = 1'b0;
      end
    end
  end

  always_comb begin
    max_bits_i = ((pixels_in_group_in * bits_per_pixel) + 15) >>> 4;
    adjusted_fullness_i = buffer_fullness_in;
    bug_fix_condition_i = (bits_per_pixel * slice_width_in) & 15;
    force_mpp_calc = 1'b0;
    if (((bug_fix_condition_i != 0) &&
         (num_bits_chunk_in + max_bits_i + 8 == chunk_size * 8)) ||
        (num_bits_chunk_in + max_bits_i + 8 > chunk_size * 8)) begin
      adjusted_fullness_i = adjusted_fullness_i - 8;
      if (adjusted_fullness_i <
          (max_bits_i - $signed({1'b0, units_per_group})))
        force_mpp_calc = 1'b1;
    end
    else if ((vbr_enable == 1'b0) && (pixel_count_in >= initial_xmit_delay) &&
             (adjusted_fullness_i <
              (max_bits_i - $signed({1'b0, units_per_group})))) begin
      force_mpp_calc = 1'b1;
    end
  end

  always_comb begin
    enc_balance_mem_read_req = '0;
    enc_balance_mem_read_addr = '{default:'0};
    enc_balance_mem_write_req = '0;
    enc_balance_mem_write_addr = '{default:'0};
    enc_balance_mem_write_data = '{default:'0};
    enc_balance_mem_write_bit_mask = '{default:'0};
    vlc_unit_enc_balance_mem_read_valid = '0;
    vlc_unit_enc_balance_mem_read_data = '{default:'0};
    vlc_unit_enc_balance_mem_write_ready = '0;
    process_group_enc_balance_mem_read_valid = '0;
    process_group_enc_balance_mem_read_data = '{default:'0};
    process_group_enc_balance_mem_write_ready = '0;
    shifter_mem_read_req = '0;
    shifter_mem_read_addr = '{default:'0};
    shifter_mem_write_req = '0;
    shifter_mem_write_addr = '{default:'0};
    shifter_mem_write_data = '{default:'0};
    shifter_mem_write_bit_mask = '{default:'0};
    vlc_unit_shifter_mem_read_valid = '0;
    vlc_unit_shifter_mem_read_data = '{default:'0};
    vlc_unit_shifter_mem_write_ready = '0;
    process_group_shifter_mem_read_valid = '0;
    process_group_shifter_mem_read_data = '{default:'0};
    process_group_shifter_mem_write_ready = '0;
    se_size_mem_read_req = '0;
    se_size_mem_read_addr = '{default:'0};
    se_size_mem_write_req = '0;
    se_size_mem_write_addr = '{default:'0};
    se_size_mem_write_data = '{default:'0};
    se_size_mem_write_bit_mask = '{default:'0};
    vlc_unit_se_size_mem_read_valid = '0;
    vlc_unit_se_size_mem_read_data = '{default:'0};
    vlc_unit_se_size_mem_write_ready = '0;
    process_group_se_size_mem_read_valid = '0;
    process_group_se_size_mem_read_data = '{default:'0};
    process_group_se_size_mem_write_ready = '0;
    frame_mem_write_req = 1'b0;
    frame_mem_write_addr = '0;
    frame_mem_write_data = 8'h00;
    frame_mem_write_bit_mask = 8'h00;
    process_group_frame_mem_write_ready = 1'b0;
    if (state_r == ST_VLC_WAIT) begin
      enc_balance_mem_read_req = vlc_unit_enc_balance_mem_read_req;
      enc_balance_mem_read_addr = vlc_unit_enc_balance_mem_read_addr;
      enc_balance_mem_write_req = vlc_unit_enc_balance_mem_write_req;
      enc_balance_mem_write_addr = vlc_unit_enc_balance_mem_write_addr;
      enc_balance_mem_write_data = vlc_unit_enc_balance_mem_write_data;
      enc_balance_mem_write_bit_mask = vlc_unit_enc_balance_mem_write_bit_mask;
      vlc_unit_enc_balance_mem_read_valid = enc_balance_mem_read_valid;
      vlc_unit_enc_balance_mem_read_data = enc_balance_mem_read_data;
      vlc_unit_enc_balance_mem_write_ready = enc_balance_mem_write_ready;
      shifter_mem_read_req = vlc_unit_shifter_mem_read_req;
      shifter_mem_read_addr = vlc_unit_shifter_mem_read_addr;
      shifter_mem_write_req = vlc_unit_shifter_mem_write_req;
      shifter_mem_write_addr = vlc_unit_shifter_mem_write_addr;
      shifter_mem_write_data = vlc_unit_shifter_mem_write_data;
      shifter_mem_write_bit_mask = vlc_unit_shifter_mem_write_bit_mask;
      vlc_unit_shifter_mem_read_valid = shifter_mem_read_valid;
      vlc_unit_shifter_mem_read_data = shifter_mem_read_data;
      vlc_unit_shifter_mem_write_ready = shifter_mem_write_ready;
      se_size_mem_read_req = vlc_unit_se_size_mem_read_req;
      se_size_mem_read_addr = vlc_unit_se_size_mem_read_addr;
      se_size_mem_write_req = vlc_unit_se_size_mem_write_req;
      se_size_mem_write_addr = vlc_unit_se_size_mem_write_addr;
      se_size_mem_write_data = vlc_unit_se_size_mem_write_data;
      se_size_mem_write_bit_mask = vlc_unit_se_size_mem_write_bit_mask;
      vlc_unit_se_size_mem_read_valid = se_size_mem_read_valid;
      vlc_unit_se_size_mem_read_data = se_size_mem_read_data;
      vlc_unit_se_size_mem_write_ready = se_size_mem_write_ready;
    end
    else if (state_r == ST_PROCESS_WAIT) begin
      enc_balance_mem_read_req = process_group_enc_balance_mem_read_req;
      enc_balance_mem_read_addr = process_group_enc_balance_mem_read_addr;
      enc_balance_mem_write_req = process_group_enc_balance_mem_write_req;
      enc_balance_mem_write_addr = process_group_enc_balance_mem_write_addr;
      enc_balance_mem_write_data = process_group_enc_balance_mem_write_data;
      enc_balance_mem_write_bit_mask = process_group_enc_balance_mem_write_bit_mask;
      process_group_enc_balance_mem_read_valid = enc_balance_mem_read_valid;
      process_group_enc_balance_mem_read_data = enc_balance_mem_read_data;
      process_group_enc_balance_mem_write_ready = enc_balance_mem_write_ready;
      shifter_mem_read_req = process_group_shifter_mem_read_req;
      shifter_mem_read_addr = process_group_shifter_mem_read_addr;
      shifter_mem_write_req = process_group_shifter_mem_write_req;
      shifter_mem_write_addr = process_group_shifter_mem_write_addr;
      shifter_mem_write_data = process_group_shifter_mem_write_data;
      shifter_mem_write_bit_mask = process_group_shifter_mem_write_bit_mask;
      process_group_shifter_mem_read_valid = shifter_mem_read_valid;
      process_group_shifter_mem_read_data = shifter_mem_read_data;
      process_group_shifter_mem_write_ready = shifter_mem_write_ready;
      se_size_mem_read_req = process_group_se_size_mem_read_req;
      se_size_mem_read_addr = process_group_se_size_mem_read_addr;
      se_size_mem_write_req = process_group_se_size_mem_write_req;
      se_size_mem_write_addr = process_group_se_size_mem_write_addr;
      se_size_mem_write_data = process_group_se_size_mem_write_data;
      se_size_mem_write_bit_mask = process_group_se_size_mem_write_bit_mask;
      process_group_se_size_mem_read_valid = se_size_mem_read_valid;
      process_group_se_size_mem_read_data = se_size_mem_read_data;
      process_group_se_size_mem_write_ready = se_size_mem_write_ready;
      frame_mem_write_req = process_group_frame_mem_write_req;
      frame_mem_write_addr = process_group_frame_mem_write_addr;
      frame_mem_write_data = process_group_frame_mem_write_data;
      frame_mem_write_bit_mask = process_group_frame_mem_write_bit_mask;
      process_group_frame_mem_write_ready = frame_mem_write_ready;
    end
    if (state_r == ST_SE_WRITE) begin
      se_size_mem_write_req[ssp_index_r] = 1'b1;
      se_size_mem_write_addr[ssp_index_r] = se_size_write_ptr_r[ssp_index_r] >> 3;
      se_size_mem_write_data[ssp_index_r] = se_write_data_r;
      se_size_mem_write_bit_mask[ssp_index_r] = 8'hff;
    end
  end

  assign num_bits_out = num_bits_r;
  assign buffer_fullness_out = buffer_fullness_r;
  assign num_bits_chunk_out = num_bits_chunk_r;
  assign pixels_in_group_out = pixels_in_group_r;
  assign slice_width_out = slice_width_r;
  assign pixel_count_out = pixel_count_r;
  assign group_count_out = group_count_r;
  assign primary_qp_out = primary_qp_r;
  assign prev_primary_qp_out = prev_primary_qp_r;
  assign prev_num_bits_out = prev_num_bits_r;
  assign coded_group_size_out = coded_group_size_r;
  assign group_count_line_out = group_count_line_r;
  assign force_mpp_out = force_mpp_r;
  assign post_mux_num_bits_out = post_mux_num_bits_r;
  assign busy = (state_r != ST_IDLE) && (state_r != ST_DONE) && (state_r != ST_ERROR);
  assign done = (state_r == ST_DONE) || (state_r == ST_ERROR);
  assign domain_valid = domain_valid_r && !fatal_error_r;
  assign illegal_domain = illegal_domain_r;
  assign fatal_error = fatal_error_r;
  assign bound_violation = bound_violation_r;
  assign child_error = child_error_r;
  assign fifo_underflow = fifo_underflow_r;
  assign fifo_overflow = fifo_overflow_r;
  assign se_size_overflow = se_size_overflow_r;
  assign buffer_overflow = buffer_overflow_r;
  assign vlc_unit_start = (state_r == ST_VLC_START);
  assign vlc_unit_index = unit_index_r;
  assign vlc_unit_force_p1_ich2 = force_p1_ich2_r;
  assign vlc_unit_num_bits_in = num_bits_r;
  assign vlc_unit_primary_qp_in = primary_qp_r;
  assign process_group_start = (state_r == ST_PROCESS_START);
  assign process_group_is_encoder = is_encoder;
  assign process_group_num_ssps = num_ssps;
  assign process_group_mux_word_size = mux_word_size;
  assign process_group_frame_capacity_bits = frame_capacity_bits;
  assign process_group_post_mux_num_bits_in = post_mux_num_bits_r;
  assign enc_balance_size_bits_out = enc_balance_size_bits_r;
  assign enc_balance_fullness_out = enc_balance_fullness_r;
  assign enc_balance_read_ptr_out = enc_balance_read_ptr_r;
  assign enc_balance_write_ptr_out = enc_balance_write_ptr_r;
  assign enc_balance_max_fullness_out = enc_balance_max_fullness_r;
  assign enc_balance_byte_ctr_out = enc_balance_byte_ctr_r;
  assign shifter_size_bits_out = shifter_size_bits_r;
  assign shifter_fullness_out = shifter_fullness_r;
  assign shifter_read_ptr_out = shifter_read_ptr_r;
  assign shifter_write_ptr_out = shifter_write_ptr_r;
  assign shifter_max_fullness_out = shifter_max_fullness_r;
  assign shifter_byte_ctr_out = shifter_byte_ctr_r;
  assign se_size_size_bits_out = se_size_size_bits_r;
  assign se_size_fullness_out = se_size_fullness_r;
  assign se_size_read_ptr_out = se_size_read_ptr_r;
  assign se_size_write_ptr_out = se_size_write_ptr_r;
  assign se_size_max_fullness_out = se_size_max_fullness_r;
  assign se_size_byte_ctr_out = se_size_byte_ctr_r;
  assign midpoint_selected_out[0] = midpoint_selected_r[0];
  assign quantized_residual_out[0][0] = quantized_residual_in[0][0];
  assign quantized_residual_mid_out[0][0] = quantized_residual_mid_in[0][0];
  assign quantized_residual_out[0][1] = quantized_residual_in[0][1];
  assign quantized_residual_mid_out[0][1] = quantized_residual_mid_in[0][1];
  assign quantized_residual_out[0][2] = quantized_residual_in[0][2];
  assign quantized_residual_mid_out[0][2] = quantized_residual_mid_in[0][2];
  assign midpoint_selected_out[1] = midpoint_selected_r[1];
  assign quantized_residual_out[1][0] = quantized_residual_in[1][0];
  assign quantized_residual_mid_out[1][0] = quantized_residual_mid_in[1][0];
  assign quantized_residual_out[1][1] = quantized_residual_in[1][1];
  assign quantized_residual_mid_out[1][1] = quantized_residual_mid_in[1][1];
  assign quantized_residual_out[1][2] = quantized_residual_in[1][2];
  assign quantized_residual_mid_out[1][2] = quantized_residual_mid_in[1][2];
  assign midpoint_selected_out[2] = midpoint_selected_r[2];
  assign quantized_residual_out[2][0] = quantized_residual_in[2][0];
  assign quantized_residual_mid_out[2][0] = quantized_residual_mid_in[2][0];
  assign quantized_residual_out[2][1] = quantized_residual_in[2][1];
  assign quantized_residual_mid_out[2][1] = quantized_residual_mid_in[2][1];
  assign quantized_residual_out[2][2] = quantized_residual_in[2][2];
  assign quantized_residual_mid_out[2][2] = quantized_residual_mid_in[2][2];
  assign midpoint_selected_out[3] = midpoint_selected_r[3];
  assign quantized_residual_out[3][0] = quantized_residual_in[3][0];
  assign quantized_residual_mid_out[3][0] = quantized_residual_mid_in[3][0];
  assign quantized_residual_out[3][1] = quantized_residual_in[3][1];
  assign quantized_residual_mid_out[3][1] = quantized_residual_mid_in[3][1];
  assign quantized_residual_out[3][2] = quantized_residual_in[3][2];
  assign quantized_residual_mid_out[3][2] = quantized_residual_mid_in[3][2];
  assign vlc_unit_enc_balance_size_bits_in = enc_balance_size_bits_r;
  assign process_group_enc_balance_size_bits_in = enc_balance_size_bits_r;
  assign vlc_unit_enc_balance_fullness_in = enc_balance_fullness_r;
  assign process_group_enc_balance_fullness_in = enc_balance_fullness_r;
  assign vlc_unit_enc_balance_read_ptr_in = enc_balance_read_ptr_r;
  assign process_group_enc_balance_read_ptr_in = enc_balance_read_ptr_r;
  assign vlc_unit_enc_balance_write_ptr_in = enc_balance_write_ptr_r;
  assign process_group_enc_balance_write_ptr_in = enc_balance_write_ptr_r;
  assign vlc_unit_enc_balance_max_fullness_in = enc_balance_max_fullness_r;
  assign process_group_enc_balance_max_fullness_in = enc_balance_max_fullness_r;
  assign vlc_unit_enc_balance_byte_ctr_in = enc_balance_byte_ctr_r;
  assign process_group_enc_balance_byte_ctr_in = enc_balance_byte_ctr_r;
  assign vlc_unit_shifter_size_bits_in = shifter_size_bits_r;
  assign process_group_shifter_size_bits_in = shifter_size_bits_r;
  assign vlc_unit_shifter_fullness_in = shifter_fullness_r;
  assign process_group_shifter_fullness_in = shifter_fullness_r;
  assign vlc_unit_shifter_read_ptr_in = shifter_read_ptr_r;
  assign process_group_shifter_read_ptr_in = shifter_read_ptr_r;
  assign vlc_unit_shifter_write_ptr_in = shifter_write_ptr_r;
  assign process_group_shifter_write_ptr_in = shifter_write_ptr_r;
  assign vlc_unit_shifter_max_fullness_in = shifter_max_fullness_r;
  assign process_group_shifter_max_fullness_in = shifter_max_fullness_r;
  assign vlc_unit_shifter_byte_ctr_in = shifter_byte_ctr_r;
  assign process_group_shifter_byte_ctr_in = shifter_byte_ctr_r;
  assign vlc_unit_se_size_size_bits_in = se_size_size_bits_r;
  assign process_group_se_size_size_bits_in = se_size_size_bits_r;
  assign vlc_unit_se_size_fullness_in = se_size_fullness_r;
  assign process_group_se_size_fullness_in = se_size_fullness_r;
  assign vlc_unit_se_size_read_ptr_in = se_size_read_ptr_r;
  assign process_group_se_size_read_ptr_in = se_size_read_ptr_r;
  assign vlc_unit_se_size_write_ptr_in = se_size_write_ptr_r;
  assign process_group_se_size_write_ptr_in = se_size_write_ptr_r;
  assign vlc_unit_se_size_max_fullness_in = se_size_max_fullness_r;
  assign process_group_se_size_max_fullness_in = se_size_max_fullness_r;
  assign vlc_unit_se_size_byte_ctr_in = se_size_byte_ctr_r;
  assign process_group_se_size_byte_ctr_in = se_size_byte_ctr_r;

  function automatic [31:0] advance_byte_ptr(
      input [31:0] pointer,
      input [31:0] size_bits
  );
    begin
      if ((size_bits == 0) || ((pointer + 32'd8) >= size_bits))
        advance_byte_ptr = 32'd0;
      else
        advance_byte_ptr = pointer + 32'd8;
    end
  endfunction

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state_r <= ST_IDLE;
      unit_index_r <= 3'd0;
      ssp_index_r <= 3'd0;
      cycle_count_r <= 32'd0;
      se_delta_r <= 32'd0;
      se_write_data_r <= 8'd0;
      num_bits_r <= 32'sd0;
      buffer_fullness_r <= 32'sd0;
      num_bits_chunk_r <= 32'sd0;
      pixels_in_group_r <= 32'sd0;
      slice_width_r <= 32'sd0;
      pixel_count_r <= 32'sd0;
      group_count_r <= 32'sd0;
      primary_qp_r <= 32'sd0;
      prev_primary_qp_r <= 32'sd0;
      prev_num_bits_r <= 32'sd0;
      coded_group_size_r <= 32'sd0;
      group_count_line_r <= 32'sd0;
      force_mpp_r <= 32'sd0;
      force_p1_ich2_r <= 32'sd0;
      domain_valid_r <= 1'b0;
      illegal_domain_r <= 1'b0;
      fatal_error_r <= 1'b0;
      bound_violation_r <= 1'b0;
      child_error_r <= 1'b0;
      fifo_underflow_r <= 1'b0;
      fifo_overflow_r <= 1'b0;
      se_size_overflow_r <= 1'b0;
      buffer_overflow_r <= 1'b0;
      for (reset_i = 0; reset_i < MAX_SSPS; reset_i = reset_i + 1) begin
        enc_balance_size_bits_r[reset_i] <= 32'd0;
        enc_balance_fullness_r[reset_i] <= 32'd0;
        enc_balance_read_ptr_r[reset_i] <= 32'd0;
        enc_balance_write_ptr_r[reset_i] <= 32'd0;
        enc_balance_max_fullness_r[reset_i] <= 32'd0;
        enc_balance_byte_ctr_r[reset_i] <= 32'd0;
        shifter_size_bits_r[reset_i] <= 32'd0;
        shifter_fullness_r[reset_i] <= 32'd0;
        shifter_read_ptr_r[reset_i] <= 32'd0;
        shifter_write_ptr_r[reset_i] <= 32'd0;
        shifter_max_fullness_r[reset_i] <= 32'd0;
        shifter_byte_ctr_r[reset_i] <= 32'd0;
        se_size_size_bits_r[reset_i] <= 32'd0;
        se_size_fullness_r[reset_i] <= 32'd0;
        se_size_read_ptr_r[reset_i] <= 32'd0;
        se_size_write_ptr_r[reset_i] <= 32'd0;
        se_size_max_fullness_r[reset_i] <= 32'd0;
        se_size_byte_ctr_r[reset_i] <= 32'd0;
        start_fullness_r[reset_i] <= 32'd0;
      end
      for (reset_i = 0; reset_i < MAX_UNITS; reset_i = reset_i + 1)
        midpoint_selected_r[reset_i] <= 32'sd0;
    end
    else if ((state_r != ST_IDLE) && (state_r != ST_DONE) &&
             (state_r != ST_ERROR) && (cycle_count_r >= MAX_CYCLES - 1)) begin
      bound_violation_r <= 1'b1;
      fatal_error_r <= 1'b1;
      domain_valid_r <= 1'b0;
      state_r <= ST_ERROR;
    end
    else begin
      if ((state_r != ST_IDLE) && (state_r != ST_DONE) && (state_r != ST_ERROR))
        cycle_count_r <= cycle_count_r + 32'd1;
      case (state_r)
        ST_IDLE: begin
          if (start) begin
            cycle_count_r <= 32'd0;
            illegal_domain_r <= 1'b0;
            fatal_error_r <= 1'b0;
            bound_violation_r <= 1'b0;
            child_error_r <= 1'b0;
            fifo_underflow_r <= 1'b0;
            fifo_overflow_r <= 1'b0;
            se_size_overflow_r <= 1'b0;
            buffer_overflow_r <= 1'b0;
            domain_valid_r <= input_legal;
            if (!input_legal) begin
              illegal_domain_r <= 1'b1;
              fatal_error_r <= 1'b1;
              state_r <= ST_ERROR;
            end
            else begin
              num_bits_r <= num_bits_in;
              buffer_fullness_r <= buffer_fullness_in;
              num_bits_chunk_r <= num_bits_chunk_in;
              pixels_in_group_r <= pixels_in_group_in;
              slice_width_r <= slice_width_in;
              pixel_count_r <= pixel_count_in;
              group_count_r <= group_count_in;
              primary_qp_r <= primary_qp_in;
              prev_primary_qp_r <= prev_primary_qp_in;
              prev_num_bits_r <= prev_num_bits_in;
              coded_group_size_r <= coded_group_size_in;
              group_count_line_r <= group_count_line_in;
              force_mpp_r <= force_mpp_in;
              post_mux_num_bits_r <= post_mux_num_bits_in;
              for (reset_i = 0; reset_i < MAX_SSPS; reset_i = reset_i + 1) begin
        enc_balance_size_bits_r[reset_i] <= enc_balance_size_bits_in[reset_i];
        enc_balance_fullness_r[reset_i] <= enc_balance_fullness_in[reset_i];
        enc_balance_read_ptr_r[reset_i] <= enc_balance_read_ptr_in[reset_i];
        enc_balance_write_ptr_r[reset_i] <= enc_balance_write_ptr_in[reset_i];
        enc_balance_max_fullness_r[reset_i] <= enc_balance_max_fullness_in[reset_i];
        enc_balance_byte_ctr_r[reset_i] <= enc_balance_byte_ctr_in[reset_i];
        shifter_size_bits_r[reset_i] <= shifter_size_bits_in[reset_i];
        shifter_fullness_r[reset_i] <= shifter_fullness_in[reset_i];
        shifter_read_ptr_r[reset_i] <= shifter_read_ptr_in[reset_i];
        shifter_write_ptr_r[reset_i] <= shifter_write_ptr_in[reset_i];
        shifter_max_fullness_r[reset_i] <= shifter_max_fullness_in[reset_i];
        shifter_byte_ctr_r[reset_i] <= shifter_byte_ctr_in[reset_i];
        se_size_size_bits_r[reset_i] <= se_size_size_bits_in[reset_i];
        se_size_fullness_r[reset_i] <= se_size_fullness_in[reset_i];
        se_size_read_ptr_r[reset_i] <= se_size_read_ptr_in[reset_i];
        se_size_write_ptr_r[reset_i] <= se_size_write_ptr_in[reset_i];
        se_size_max_fullness_r[reset_i] <= se_size_max_fullness_in[reset_i];
        se_size_byte_ctr_r[reset_i] <= se_size_byte_ctr_in[reset_i];
              end
              for (reset_i = 0; reset_i < MAX_UNITS; reset_i = reset_i + 1)
                midpoint_selected_r[reset_i] <= midpoint_selected_in[reset_i];
              state_r <= ST_INIT;
            end
          end
        end

        ST_INIT: begin
          // Exact source order: clear unit midpoint markers, then snapshot FIFO fullness.
          for (reset_i = 0; reset_i < MAX_UNITS; reset_i = reset_i + 1)
            midpoint_selected_r[reset_i] <=
                (reset_i < units_per_group) ? 32'sd0 : midpoint_selected_r[reset_i];
          for (reset_i = 0; reset_i < MAX_SSPS; reset_i = reset_i + 1)
            start_fullness_r[reset_i] <= enc_balance_fullness_r[reset_i];
          prev_num_bits_r <= num_bits_r;
          force_mpp_r <= force_mpp_calc ? 32'sd1 : 32'sd0;
          unit_index_r <= 3'd0;
          ssp_index_r <= 3'd0;
          state_r <= ST_VLC_START;
        end

        ST_VLC_START: begin
          if (vlc_unit_ready)
            state_r <= ST_VLC_WAIT;
        end

        ST_VLC_WAIT: begin
          if (vlc_unit_done) begin
            if (!vlc_unit_domain_valid || vlc_unit_fatal_error) begin
              child_error_r <= 1'b1;
              illegal_domain_r <= !vlc_unit_domain_valid;
              fatal_error_r <= 1'b1;
              domain_valid_r <= 1'b0;
              state_r <= ST_ERROR;
            end
            else begin
              num_bits_r <= vlc_unit_num_bits_out;
              primary_qp_r <= vlc_unit_primary_qp_out;
              for (k = 0; k < MAX_SSPS; k = k + 1) begin
              enc_balance_size_bits_r[k] <= vlc_unit_enc_balance_size_bits_out[k];
              enc_balance_fullness_r[k] <= vlc_unit_enc_balance_fullness_out[k];
              enc_balance_read_ptr_r[k] <= vlc_unit_enc_balance_read_ptr_out[k];
              enc_balance_write_ptr_r[k] <= vlc_unit_enc_balance_write_ptr_out[k];
              enc_balance_max_fullness_r[k] <= vlc_unit_enc_balance_max_fullness_out[k];
              enc_balance_byte_ctr_r[k] <= vlc_unit_enc_balance_byte_ctr_out[k];
              end
              if (unit_index_r + 3'd1 < units_per_group) begin
                unit_index_r <= unit_index_r + 3'd1;
                state_r <= ST_VLC_START;
              end
              else begin
                ssp_index_r <= 3'd0;
                state_r <= ST_SE_PREP;
              end
            end
          end
        end

        ST_SE_PREP: begin
          if (ssp_index_r >= num_ssps) begin
            state_r <= ST_PROCESS_CHECK;
          end
          else if (enc_balance_fullness_r[ssp_index_r] < start_fullness_r[ssp_index_r]) begin
            fifo_underflow_r <= 1'b1;
            fatal_error_r <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            se_delta_r <= enc_balance_fullness_r[ssp_index_r] - start_fullness_r[ssp_index_r];
            se_write_data_r <= enc_balance_fullness_r[ssp_index_r] - start_fullness_r[ssp_index_r];
            if ((enc_balance_fullness_r[ssp_index_r] - start_fullness_r[ssp_index_r]) > MAX_SE_SIZE) begin
              se_size_overflow_r <= 1'b1;
              illegal_domain_r <= 1'b1;
              fatal_error_r <= 1'b1;
              domain_valid_r <= 1'b0;
              state_r <= ST_ERROR;
            end
            else if ((enc_balance_fullness_r[ssp_index_r] - start_fullness_r[ssp_index_r]) > max_se_size[ssp_index_r]) begin
              se_size_overflow_r <= 1'b1;
              fatal_error_r <= 1'b1;
              state_r <= ST_ERROR;
            end
            else if ((se_size_fullness_r[ssp_index_r] + 32'd8) >
                     se_size_size_bits_r[ssp_index_r]) begin
              fifo_overflow_r <= 1'b1;
              fatal_error_r <= 1'b1;
              state_r <= ST_ERROR;
            end
            else begin
              state_r <= ST_SE_WRITE;
            end
          end
        end

        ST_SE_WRITE: begin
          if (se_size_mem_write_ready[ssp_index_r]) begin
            se_size_fullness_r[ssp_index_r] <= se_size_fullness_r[ssp_index_r] + 32'd8;
            se_size_write_ptr_r[ssp_index_r] <= advance_byte_ptr(
                se_size_write_ptr_r[ssp_index_r], se_size_size_bits_r[ssp_index_r]);
            if ((se_size_fullness_r[ssp_index_r] + 32'd8) >
                se_size_max_fullness_r[ssp_index_r])
              se_size_max_fullness_r[ssp_index_r] <=
                  se_size_fullness_r[ssp_index_r] + 32'd8;
            if (ssp_index_r + 3'd1 < num_ssps) begin
              ssp_index_r <= ssp_index_r + 3'd1;
              state_r <= ST_SE_PREP;
            end
            else begin
              state_r <= ST_PROCESS_CHECK;
            end
          end
        end

        ST_PROCESS_CHECK: begin
          if (group_count_r >
              ($signed({1'b0, mux_word_size}) + active_max_se_size - 32'sd3))
            state_r <= ST_PROCESS_START;
          else
            state_r <= ST_ACCOUNT;
        end

        ST_PROCESS_START: begin
          if (process_group_ready)
            state_r <= ST_PROCESS_WAIT;
        end

        ST_PROCESS_WAIT: begin
          if (process_group_done) begin
            if (!process_group_domain_valid || process_group_fatal_error) begin
              child_error_r <= 1'b1;
              illegal_domain_r <= !process_group_domain_valid;
              fatal_error_r <= 1'b1;
              domain_valid_r <= 1'b0;
              state_r <= ST_ERROR;
            end
            else begin
              post_mux_num_bits_r <= process_group_post_mux_num_bits_out;
              for (k = 0; k < MAX_SSPS; k = k + 1) begin
              enc_balance_size_bits_r[k] <= process_group_enc_balance_size_bits_out[k];
              enc_balance_fullness_r[k] <= process_group_enc_balance_fullness_out[k];
              enc_balance_read_ptr_r[k] <= process_group_enc_balance_read_ptr_out[k];
              enc_balance_write_ptr_r[k] <= process_group_enc_balance_write_ptr_out[k];
              enc_balance_max_fullness_r[k] <= process_group_enc_balance_max_fullness_out[k];
              enc_balance_byte_ctr_r[k] <= process_group_enc_balance_byte_ctr_out[k];
              shifter_size_bits_r[k] <= process_group_shifter_size_bits_out[k];
              shifter_fullness_r[k] <= process_group_shifter_fullness_out[k];
              shifter_read_ptr_r[k] <= process_group_shifter_read_ptr_out[k];
              shifter_write_ptr_r[k] <= process_group_shifter_write_ptr_out[k];
              shifter_max_fullness_r[k] <= process_group_shifter_max_fullness_out[k];
              shifter_byte_ctr_r[k] <= process_group_shifter_byte_ctr_out[k];
              se_size_size_bits_r[k] <= process_group_se_size_size_bits_out[k];
              se_size_fullness_r[k] <= process_group_se_size_fullness_out[k];
              se_size_read_ptr_r[k] <= process_group_se_size_read_ptr_out[k];
              se_size_write_ptr_r[k] <= process_group_se_size_write_ptr_out[k];
              se_size_max_fullness_r[k] <= process_group_se_size_max_fullness_out[k];
              se_size_byte_ctr_r[k] <= process_group_se_size_byte_ctr_out[k];
              end
              state_r <= ST_ACCOUNT;
            end
          end
        end

        ST_ACCOUNT: begin
          buffer_fullness_r <= buffer_fullness_r + (num_bits_r - prev_num_bits_r);
          coded_group_size_r <= num_bits_r - prev_num_bits_r;
          prev_primary_qp_r <= primary_qp_r;
          group_count_line_r <= group_count_line_r + 32'sd1;
          if ((buffer_fullness_r + (num_bits_r - prev_num_bits_r)) > rcb_bits) begin
            buffer_overflow_r <= 1'b1;
            fatal_error_r <= 1'b1;
            state_r <= ST_ERROR;
          end
          else begin
            state_r <= ST_DONE;
          end
        end

        ST_DONE: begin
          state_r <= ST_IDLE;
        end

        ST_ERROR: begin
          state_r <= ST_IDLE;
        end

        default: begin
          illegal_domain_r <= 1'b1;
          fatal_error_r <= 1'b1;
          domain_valid_r <= 1'b0;
          state_r <= ST_ERROR;
        end
      endcase
    end
  end

endmodule
