#!/usr/bin/env python3
"""Emit the executable overlay for the Encode RateControl transition.

The rate-control RTL is generated by ``generate_rate_control_encode.py``.
This module owns the ABI and caller boundary around that RTL.  In particular,
the immutable C function is called against a private state/chunk window, so a
shadow run cannot accidentally become a C commit.  The public function is
kept deliberately small because it is also used by source-generation tests
without importing the CI/CD agent's large dispatch table.
"""

from __future__ import annotations

import hashlib
import pathlib
import re
from typing import Any, Iterable


CONFIG_FIELDS = (
    "bits_per_component",
    "bits_per_pixel",
    "chunk_size",
    "dsc_version_minor",
    "initial_xmit_delay",
    "native_420",
    "native_422",
    "rc_edge_factor",
    "rc_model_size",
    "rc_quant_incr_limit0",
    "rc_quant_incr_limit1",
    "rc_tgt_offset_hi",
    "rc_tgt_offset_lo",
    "rcb_bits",
    "vbr_enable",
)

STATE_FIELDS = (
    "bitSaveMode",
    "bitsClamped",
    "bpgFracAccum",
    "bufferFullness",
    "chunkCount",
    "chunkPixelTimes",
    "codedGroupSize",
    "errorOccurred",
    "firstFlat",
    "ichSelected",
    "isEncoder",
    "mppState",
    "numBitsChunk",
    "pixelCount",
    "prevQp",
    "prevRange",
    "rcSizeGroup",
    "sliceWidth",
    "stQp",
    "unitsPerGroup",
    "vPos",
)

STATE_OUTPUT_FIELDS = (
    "bitSaveMode",
    "bitsClamped",
    "bpgFracAccum",
    "bufferFullness",
    "chunkCount",
    "chunkPixelTimes",
    "errorOccurred",
    "mppState",
    "numBitsChunk",
    "pixelCount",
    "prevQp",
    "prevRange",
    "rcSizeGroup",
    "stQp",
)

FATAL_FIELDS = ("domain_valid", "fatal_error", "fatal_error_code")
MAX_EVENTS = 3
IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
HASH = re.compile(r"^[0-9a-fA-F]{64}$")


def _safe_identifier(value: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", str(value))
    if not result or result[0].isdigit():
        result = "c_" + result
    return result


def _lower_identifier(value: str) -> str:
    return _safe_identifier(value).lower()


def _path_hash(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _write(path: pathlib.Path, text: str) -> pathlib.Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    return path


def _parameters(agent: Any, contract: dict[str, Any]) -> list[dict[str, Any]]:
    function = contract.get("function", {}) or {}
    direct = function.get("parameters")
    if isinstance(direct, list) and direct:
        return [dict(item) for item in direct]
    getter = getattr(agent, "function_parameters", None)
    if callable(getter):
        value = getter(contract)
        if isinstance(value, list):
            return [dict(item) for item in value]
    return []


def _resolve_reference(agent: Any, root: pathlib.Path, value: str) -> pathlib.Path:
    resolver = getattr(agent, "resolve_artifact_reference", None)
    if callable(resolver):
        return pathlib.Path(resolver(value))
    path = pathlib.Path(value)
    return path if path.is_absolute() else root / path


def _validate_hash_pinned_dependency(
    agent: Any, contract: dict[str, Any], source_dir: pathlib.Path
) -> tuple[dict[str, Any], pathlib.Path | None]:
    dependencies = contract.get("dependencies", []) or []
    if not isinstance(dependencies, list) or len(dependencies) != 1:
        raise RuntimeError("Encode rate-control requires one pinned child dependency")
    dependency = dict(dependencies[0])
    if dependency.get("role") != "remove_one_pixel_bits":
        raise RuntimeError("Encode rate-control child role changed")
    if not str(dependency.get("contract_id", "")):
        raise RuntimeError("Encode rate-control child contract id is missing")
    for key in ("contract_sha256", "module_sha256"):
        if not HASH.fullmatch(str(dependency.get(key, ""))):
            raise RuntimeError(f"Encode rate-control child {key} is not hash pinned")
    module = str(dependency.get("module", ""))
    if not IDENTIFIER.fullmatch(module):
        raise RuntimeError("Encode rate-control child module is not an identifier")

    root_value = getattr(agent, "root", None)
    root = pathlib.Path(root_value) if root_value else source_dir.parent
    contract_path = _resolve_reference(agent, root, str(dependency.get("contract_file", "")))
    module_path = _resolve_reference(agent, root, str(dependency.get("module_file", "")))
    # A source-generation fixture may carry an intentionally external pin.  If
    # the pinned files are present, verify them; the hash pin itself remains a
    # required part of the contract in either case.
    if contract_path.is_file():
        if _path_hash(contract_path) != str(dependency["contract_sha256"]).lower():
            raise RuntimeError("Encode rate-control child contract hash changed")
    if module_path.is_file():
        if _path_hash(module_path) != str(dependency["module_sha256"]).lower():
            raise RuntimeError("Encode rate-control child module hash changed")
        module_text = module_path.read_text(encoding="utf-8", errors="replace")
        if not re.search(rf"\bmodule\s+{re.escape(module)}\s*\(", module_text):
            raise RuntimeError("Encode rate-control child module name changed")
    return dependency, module_path if module_path.is_file() else None


def _validate_contract(
    agent: Any, contract: dict[str, Any], source_dir: pathlib.Path
) -> dict[str, Any]:
    semantics = contract.get("semantics", {}) or {}
    bindings = semantics.get("bindings", {}) or {}
    constants = semantics.get("constants", {}) or {}
    if semantics.get("kind") != "bounded_rate_control_encode_transition":
        raise RuntimeError("contract is not bounded Encode rate control")
    if (
        int(constants.get("num_buf_ranges", 0)) != 15
        or int(constants.get("max_units", 0)) != 4
        or int(constants.get("samples_per_unit", 0)) != 3
        or int(constants.get("max_remove_stages", 0)) != 3
    ):
        raise RuntimeError("bounded Encode rate-control constants are incomplete")
    specialization = semantics.get("specialization", {}) or {}
    if (
        int(specialization.get("is_encoder", -1)) != 1
        or specialization.get("midpoint_source") != "midpointSelected"
    ):
        raise RuntimeError("Encode rate-control midpoint specialization changed")
    legal_domain = semantics.get("legal_domain", {}) or {}
    expected_domain = {
        "encoder_only": True,
        "is_encoder": [1, 1],
        "group_size": [1, 3],
        "units_per_group": [3, 4],
        "previous_range": [0, 14],
        "dsc_version_minor": [1, 2],
        "component_bit_depth": [8, 16],
        "slice_width_positive": True,
        "chunk_pixel_times_before_slice_width": True,
        "native_modes_boolean_and_mutually_exclusive": True,
        "vbr_boolean": True,
    }
    if any(legal_domain.get(key) != value for key, value in expected_domain.items()):
        raise RuntimeError("Encode rate-control legal domains changed")

    argument_ports = {
        str(key): str(value)
        for key, value in (bindings.get("argument_ports", {}) or {}).items()
    }
    config_ports = {
        str(key): str(value)
        for key, value in (bindings.get("config_ports", {}) or {}).items()
    }
    state_ports = {
        str(key): str(value)
        for key, value in (bindings.get("state_ports", {}) or {}).items()
    }
    state_output_ports = {
        str(key): str(value)
        for key, value in (bindings.get("state_output_ports", {}) or {}).items()
    }
    midpoint_ports = [str(value) for value in bindings.get("midpoint_ports", [])]
    depth_ports = [str(value) for value in bindings.get("depth_ports", [])]
    predicted_ports = [str(value) for value in bindings.get("predicted_ports", [])]
    rc_size_ports = [str(value) for value in bindings.get("rc_size_ports", [])]
    threshold_ports = [str(value) for value in bindings.get("threshold_ports", [])]
    range_ports = {
        str(key): [str(value) for value in values]
        for key, values in (bindings.get("range_ports", {}) or {}).items()
    }
    events = [
        {str(key): str(value) for key, value in item.items()}
        for item in bindings.get("chunk_event_ports", [])
    ]
    if set(argument_ports) != {
        "throttle_offset", "bpg_offset", "group_count", "scale", "group_size"
    }:
        raise RuntimeError("RateControl scalar argument bindings changed")
    if set(config_ports) != set(CONFIG_FIELDS) or set(state_ports) != set(STATE_FIELDS):
        raise RuntimeError("RateControl config/state bindings are incomplete")
    if set(state_output_ports) != set(STATE_OUTPUT_FIELDS):
        raise RuntimeError("RateControl does not expose all 14 scalar state outputs")
    if len(midpoint_ports) != 4 or len(depth_ports) != 2:
        raise RuntimeError("RateControl midpoint/component bindings are incomplete")
    if len(predicted_ports) != 4 or len(rc_size_ports) != 4:
        raise RuntimeError("RateControl predicted/size bindings are incomplete")
    if len(threshold_ports) != 14:
        raise RuntimeError("RateControl threshold bindings are incomplete")
    if set(range_ports) != {"range_min_qp", "range_max_qp", "range_bpg_offset"}:
        raise RuntimeError("RateControl range bindings are incomplete")
    if any(len(values) != 15 for values in range_ports.values()):
        raise RuntimeError("RateControl range arrays are incomplete")
    if not 1 <= len(events) <= MAX_EVENTS:
        raise RuntimeError("RateControl must expose one to three chunk events")
    for index, event in enumerate(events):
        if set(event) != {"enable", "index", "value"}:
            raise RuntimeError("RateControl chunk event binding is incomplete")
        expected = f"chunk_write_enable_{index}"
        if event["enable"] != expected:
            raise RuntimeError("RateControl chunk events are not source ordered")
    all_bound_names = [
        *argument_ports.values(),
        *config_ports.values(),
        *state_ports.values(),
        *midpoint_ports,
        *depth_ports,
        *predicted_ports,
        *rc_size_ports,
        *threshold_ports,
        *[value for values in range_ports.values() for value in values],
        *state_output_ports.values(),
        *[value for event in events for value in event.values()],
        "domain_valid",
        "fatal_error",
        "fatal_error_code",
    ]
    if any(not IDENTIFIER.fullmatch(name) for name in all_bound_names):
        raise RuntimeError("RateControl contains an invalid ABI identifier")
    if any("use_midpoint" in name or "useMidpoint" in name for name in all_bound_names):
        raise RuntimeError("decoder midpoint inputs must not enter Encode RTL")
    fatal_ports = {
        str(key): str(value)
        for key, value in (bindings.get("fatal_ports", {}) or {}).items()
    }
    if fatal_ports != {
        "domain_valid": "domain_valid",
        "fatal_error": "fatal_error",
        "fatal_error_code": "fatal_error_code",
    }:
        raise RuntimeError("RateControl fatal sideband bindings changed")
    parameters = _parameters(agent, contract)
    if len(parameters) != 7:
        raise RuntimeError("RateControl native ABI must have seven parameters")
    pointers = [item for item in parameters if item.get("pointer") or "*" in str(item.get("type", ""))]
    scalars = [item for item in parameters if item not in pointers]
    if len(pointers) != 2 or len(scalars) != 5 or any(str(item.get("type")) != "int" for item in scalars):
        raise RuntimeError("RateControl native pointer/scalar ABI changed")
    if {str(item.get("type")) for item in pointers} != {"dsc_cfg_t *", "dsc_state_t *"}:
        raise RuntimeError("RateControl native record ABI changed")
    if any(not IDENTIFIER.fullmatch(str(item.get("name", ""))) for item in parameters):
        raise RuntimeError("RateControl native parameter identifier is invalid")
    dependency, module_path = _validate_hash_pinned_dependency(agent, contract, source_dir)
    ports = [
        dict(port)
        for port in (contract.get("interface", {}) or {}).get("ports", [])
        if isinstance(port, dict)
    ]
    inputs = [port for port in ports if port.get("direction") == "input"]
    outputs = [port for port in ports if port.get("direction") == "output"]
    expected_inputs = {
        *argument_ports.values(),
        *config_ports.values(),
        *state_ports.values(),
        *midpoint_ports,
        *depth_ports,
        *predicted_ports,
        *rc_size_ports,
        *threshold_ports,
        *[value for values in range_ports.values() for value in values],
    }
    expected_outputs = {
        *fatal_ports.values(),
        *state_output_ports.values(),
        *[value for event in events for value in event.values()],
    }
    if {str(port.get("name")) for port in inputs} != expected_inputs:
        raise RuntimeError("RateControl input port set changed")
    if {str(port.get("name")) for port in outputs} != expected_outputs:
        raise RuntimeError("RateControl output port set changed")
    return {
        "semantics": semantics,
        "bindings": bindings,
        "constants": constants,
        "arguments": argument_ports,
        "config": config_ports,
        "state": state_ports,
        "outputs": state_output_ports,
        "midpoint": midpoint_ports,
        "depth": depth_ports,
        "predicted": predicted_ports,
        "rc_size": rc_size_ports,
        "thresholds": threshold_ports,
        "ranges": range_ports,
        "fatal": fatal_ports,
        "events": events,
        "parameters": parameters,
        "ports": ports,
        "inputs": inputs,
        "output_ports": outputs,
        "dependency": dependency,
        "dependency_module_path": module_path,
    }


def _parameter_specs(parameters: Iterable[dict[str, Any]]) -> tuple[str, list[str]]:
    rows = list(parameters)
    specs = [f"{str(item.get('type', 'int')).strip()} {item['name']}" for item in rows]
    names = [str(item["name"]) for item in rows]
    return ", ".join(specs), names


def _state_snapshot_source() -> str:
    fields = (
        "bitSaveMode",
        "bitsClamped",
        "bpgFracAccum",
        "bufferFullness",
        "chunkCount",
        "chunkPixelTimes",
        "errorOccurred",
        "mppState",
        "numBitsChunk",
        "pixelCount",
        "prevQp",
        "prevRange",
        "rcSizeGroup",
        "stQp",
    )
    declarations = "\n".join(f"    int {field};" for field in fields)
    saves = "\n".join(f"    saved->{field} = state->{field};" for field in fields)
    restores = "\n".join(f"    state->{field} = saved->{field};" for field in fields)
    return f"""
typedef struct dsc_cicd_rate_control_snapshot_s {{
{declarations}
}} dsc_cicd_rate_control_snapshot_t;

static void dsc_cicd_snapshot_rate_control(
    const dsc_state_t *state,
    dsc_cicd_rate_control_snapshot_t *saved) {{
{saves}
}}

static void dsc_cicd_restore_rate_control(
    dsc_state_t *state,
    const dsc_cicd_rate_control_snapshot_t *saved) {{
{restores}
}}
""".strip()


def _metrics_source() -> str:
    return """
static unsigned long dsc_cicd_calls;
static unsigned long dsc_cicd_rtl_invocations;
static unsigned long dsc_cicd_mismatches;
static int dsc_cicd_report_registered;

static void dsc_cicd_report(void) {
    fprintf(stderr, "DSC_CICD_OVERLAY_METRICS calls=%lu rtl_invocations=%lu mismatches=%lu\\n",
            dsc_cicd_calls, dsc_cicd_rtl_invocations, dsc_cicd_mismatches);
}

static void dsc_cicd_note_call(void) {
    if (!dsc_cicd_report_registered) {
        atexit(dsc_cicd_report);
        dsc_cicd_report_registered = 1;
    }
    ++dsc_cicd_calls;
}

static void dsc_cicd_note_rtl_invocation(void) {
    ++dsc_cicd_rtl_invocations;
}
""".strip()


def _abi_source(info: dict[str, Any]) -> str:
    constants = info["constants"]
    arguments = info["arguments"]
    config = info["config"]
    state = info["state"]
    outputs = info["outputs"]
    events = info["events"]
    argument_lines = "\n".join(f"    int32_t {port};" for port in arguments.values())
    config_lines = "\n".join(f"    int32_t {port};" for port in config.values())
    state_lines = "\n".join(f"    int32_t {port};" for port in state.values())
    output_lines = "\n".join(
        f"    int32_t {_lower_identifier(field)};" for field in outputs
    )
    return f"""
#ifndef DSC_CICD_RTL_ABI_H
#define DSC_CICD_RTL_ABI_H
#include <stdint.h>

#define DSC_CICD_RC_RANGES {int(constants['num_buf_ranges'])}
#define DSC_CICD_RC_UNITS {int(constants['max_units'])}
#define DSC_CICD_RC_EVENTS {len(events)}
#define DSC_CICD_RC_THRESHOLDS (DSC_CICD_RC_RANGES - 1)

typedef struct dsc_cicd_rate_control_input_s {{
{argument_lines}
{config_lines}
{state_lines}
    int32_t midpoint_selected[DSC_CICD_RC_UNITS];
    int32_t cpnt_bit_depth[2];
    int32_t predicted_size[DSC_CICD_RC_UNITS];
    int32_t rc_size_unit[DSC_CICD_RC_UNITS];
    int32_t rc_buf_thresh[DSC_CICD_RC_THRESHOLDS];
    int32_t range_min_qp[DSC_CICD_RC_RANGES];
    int32_t range_max_qp[DSC_CICD_RC_RANGES];
    int32_t range_bpg_offset[DSC_CICD_RC_RANGES];
}} dsc_cicd_rate_control_input_t;

typedef struct dsc_cicd_rate_control_output_s {{
    int32_t domain_valid;
    int32_t fatal_error;
    int32_t fatal_error_code;
{output_lines}
    int32_t chunk_write_enable[DSC_CICD_RC_EVENTS];
    int32_t chunk_write_index[DSC_CICD_RC_EVENTS];
    int32_t chunk_write_value[DSC_CICD_RC_EVENTS];
}} dsc_cicd_rate_control_output_t;

#ifdef __cplusplus
extern "C" {{
#endif
void dsc_cicd_rtl(const dsc_cicd_rate_control_input_t *input,
                  dsc_cicd_rate_control_output_t *output);
#ifdef __cplusplus
}}
#endif
#endif
""".strip()


def _header_source(parameters: list[dict[str, Any]]) -> str:
    declaration, _ = _parameter_specs(parameters)
    return f"""
#ifndef DSC_CICD_OVERLAY_H
#define DSC_CICD_OVERLAY_H
#include \"dsc_types.h\"
void dsc_cicd_invoke({declaration});
#endif
""".strip()


def _c_input_assignments(info: dict[str, Any], cfg: str, state: str) -> str:
    lines: list[str] = []
    for field, port in info["arguments"].items():
        lines.append(f"    dsc_cicd_input.{port} = {field};")
    for field, port in info["config"].items():
        lines.append(f"    dsc_cicd_input.{port} = {cfg}->{field};")
    for field, port in info["state"].items():
        lines.append(f"    dsc_cicd_input.{port} = {state}->{field};")
    for index, port in enumerate(info["midpoint"]):
        lines.append(f"    dsc_cicd_input.midpoint_selected[{index}] = {state}->midpointSelected[{index}];")
    for index, port in enumerate(info["depth"]):
        lines.append(f"    dsc_cicd_input.cpnt_bit_depth[{index}] = {state}->cpntBitDepth[{index}];")
    for index, port in enumerate(info["predicted"]):
        lines.append(f"    dsc_cicd_input.predicted_size[{index}] = {state}->predictedSize[{index}];")
    for index, port in enumerate(info["rc_size"]):
        lines.append(f"    dsc_cicd_input.rc_size_unit[{index}] = {state}->rcSizeUnit[{index}];")
    for index, port in enumerate(info["thresholds"]):
        lines.append(f"    dsc_cicd_input.rc_buf_thresh[{index}] = {cfg}->rc_buf_thresh[{index}];")
    for field in ("range_min_qp", "range_max_qp", "range_bpg_offset"):
        for index, port in enumerate(info["ranges"][field]):
            lines.append(
                f"    dsc_cicd_input.{field}[{index}] = {cfg}->rc_range_parameters[{index}].{field};"
            )
    return "\n".join(lines)


def _snapshot_apply_source(info: dict[str, Any]) -> tuple[str, str]:
    outputs = info["outputs"]
    capture = "\n".join(
        f"    output->{_lower_identifier(field)} = state->{field};"
        for field in STATE_OUTPUT_FIELDS
    )
    apply = "\n".join(
        f"    state->{field} = output->{_lower_identifier(field)};"
        for field in STATE_OUTPUT_FIELDS
    )
    # Keep the field map consumed, even when a contract uses non-default port
    # spellings.  The ABI names above are independent from RTL port names.
    if set(outputs) != set(STATE_OUTPUT_FIELDS):
        raise RuntimeError("state output map changed while rendering the adapter")
    return capture, apply


def _oracle_helpers_source(event_count: int) -> str:
    capture_lines = "\n".join(
        f"    output->{_lower_identifier(field)} = state->{field};"
        for field in STATE_OUTPUT_FIELDS
    )
    event_lines = "\n".join(
        f"    if (shadow[base + {index}] != DSC_CICD_CHUNK_SENTINEL) {{\n"
        f"        output->chunk_write_enable[{index}] = 1;\n"
        f"        output->chunk_write_index[{index}] = base + {index};\n"
        f"        output->chunk_write_value[{index}] = shadow[base + {index}];\n"
        "    }"
        for index in range(event_count)
    )
    return f"""
#define DSC_CICD_CHUNK_SENTINEL (-2147483647)

static void dsc_cicd_init_output(
    const dsc_state_t *state,
    dsc_cicd_rate_control_output_t *output) {{
    memset(output, 0, sizeof(*output));
    output->domain_valid = 1;
{capture_lines}
}}

static void dsc_cicd_capture_oracle_output(
    const dsc_state_t *state,
    const int *shadow,
    int base,
    dsc_cicd_rate_control_output_t *output) {{
    dsc_cicd_init_output(state, output);
{event_lines}
}}

static int dsc_cicd_write_all(int fd, const void *buffer, size_t size) {{
    const unsigned char *cursor = (const unsigned char *)buffer;
    while (size != 0) {{
        ssize_t written = write(fd, cursor, size);
        if (written <= 0) return 0;
        cursor += (size_t)written;
        size -= (size_t)written;
    }}
    return 1;
}}

static int dsc_cicd_read_all(int fd, void *buffer, size_t size) {{
    unsigned char *cursor = (unsigned char *)buffer;
    while (size != 0) {{
        ssize_t received = read(fd, cursor, size);
        if (received <= 0) return 0;
        cursor += (size_t)received;
        size -= (size_t)received;
    }}
    return 1;
}}

static int dsc_cicd_run_private_oracle(
    dsc_cfg_t *cfg,
    dsc_state_t *state,
    int throttle_offset,
    int bpg_offset,
    int group_count,
    int scale,
    int group_size,
    int base,
    int *shadow,
    dsc_cicd_rate_control_output_t *output) {{
    int pipe_fds[2];
    if (pipe(pipe_fds) != 0) return 0;
    dsc_state_t private_state = *state;
    private_state.chunkSizes = shadow;
    pid_t child = fork();
    if (child < 0) {{
        close(pipe_fds[0]);
        close(pipe_fds[1]);
        return 0;
    }}
    if (child == 0) {{
        dsc_cicd_rate_control_output_t child_output;
        close(pipe_fds[0]);
        {str(state)}
        {str(cfg)}
        {str(throttle_offset)}
        {str(bpg_offset)}
        {str(group_count)}
        {str(scale)}
        {str(group_size)}
        {str(base)}
        RateControl_original(cfg, &private_state, throttle_offset, bpg_offset,
                             group_count, scale, group_size);
        dsc_cicd_capture_oracle_output(&private_state, shadow, base, &child_output);
        (void)dsc_cicd_write_all(pipe_fds[1], &child_output, sizeof(child_output));
        close(pipe_fds[1]);
        _exit(0);
    }}
    close(pipe_fds[1]);
    dsc_cicd_rate_control_output_t child_output;
    int received = dsc_cicd_read_all(pipe_fds[0], &child_output, sizeof(child_output));
    close(pipe_fds[0]);
    int child_status = 0;
    (void)waitpid(child, &child_status, 0);
    if (!received || !WIFEXITED(child_status) || WEXITSTATUS(child_status) != 0) return 0;
    *output = child_output;
    return 1;
}}
""".replace(
        f"        {str(state)}\n        {str(cfg)}\n        {str(throttle_offset)}\n        {str(bpg_offset)}\n        {str(group_count)}\n        {str(scale)}\n        {str(group_size)}\n        {str(base)}\n",
        "",
    ).strip()


def _oracle_helpers_source_clean(event_count: int, original: str) -> str:
    """Render the private oracle helpers without confusing f-string braces."""
    capture_lines = "\n".join(
        f"    output->{_lower_identifier(field)} = state->{field};"
        for field in STATE_OUTPUT_FIELDS
    )
    return f"""
#define DSC_CICD_CHUNK_SENTINEL (-2147483647)

static void dsc_cicd_init_output(
    const dsc_state_t *state,
    dsc_cicd_rate_control_output_t *output) {{
    memset(output, 0, sizeof(*output));
    output->domain_valid = 1;
{capture_lines}
}}

static void dsc_cicd_capture_oracle_output(
    const dsc_state_t *state,
    const int *shadow,
    int base,
    int capacity,
    int group_size,
    int initial_pixel_count,
    int initial_chunk_pixel_times,
    int initial_xmit_delay,
    int slice_width,
    int vbr_enable,
    dsc_cicd_rate_control_output_t *output) {{
    dsc_cicd_init_output(state, output);
    int pixel_count = initial_pixel_count;
    int chunk_pixel_times = initial_chunk_pixel_times;
    int chunk_index = base;
    for (int stage = 0; stage < {event_count} && stage < group_size; ++stage) {{
        ++pixel_count;
        if (pixel_count < initial_xmit_delay)
            continue;
        ++chunk_pixel_times;
        if (chunk_pixel_times < slice_width)
            continue;
        if (vbr_enable && chunk_index >= 0 && chunk_index < capacity &&
            shadow[chunk_index] != DSC_CICD_CHUNK_SENTINEL) {{
            output->chunk_write_enable[stage] = 1;
            output->chunk_write_index[stage] = chunk_index;
            output->chunk_write_value[stage] = shadow[chunk_index];
        }}
        ++chunk_index;
        chunk_pixel_times = 0;
    }}
}}

static int dsc_cicd_write_all(int fd, const void *buffer, size_t size) {{
    const unsigned char *cursor = (const unsigned char *)buffer;
    while (size != 0) {{
        ssize_t written = write(fd, cursor, size);
        if (written <= 0) return 0;
        cursor += (size_t)written;
        size -= (size_t)written;
    }}
    return 1;
}}

static int dsc_cicd_read_all(int fd, void *buffer, size_t size) {{
    unsigned char *cursor = (unsigned char *)buffer;
    while (size != 0) {{
        ssize_t received = read(fd, cursor, size);
        if (received <= 0) return 0;
        cursor += (size_t)received;
        size -= (size_t)received;
    }}
    return 1;
}}

static int dsc_cicd_run_private_oracle(
    dsc_cfg_t *cfg,
    dsc_state_t *state,
    int throttle_offset,
    int bpg_offset,
    int group_count,
    int scale,
    int group_size,
    int base,
    int capacity,
    int *shadow,
    dsc_cicd_rate_control_output_t *output) {{
    int pipe_fds[2];
    if (pipe(pipe_fds) != 0) return 0;
    dsc_state_t private_state = *state;
    private_state.chunkSizes = shadow;
    pid_t child = fork();
    if (child < 0) {{
        close(pipe_fds[0]);
        close(pipe_fds[1]);
        return 0;
    }}
    if (child == 0) {{
        dsc_cicd_rate_control_output_t child_output;
        close(pipe_fds[0]);
        {original}(cfg, &private_state, throttle_offset, bpg_offset,
                             group_count, scale, group_size);
        dsc_cicd_capture_oracle_output(
            &private_state, shadow, base, capacity, group_size,
            state->pixelCount, state->chunkPixelTimes,
            cfg->initial_xmit_delay, state->sliceWidth, cfg->vbr_enable,
            &child_output);
        (void)dsc_cicd_write_all(pipe_fds[1], &child_output, sizeof(child_output));
        close(pipe_fds[1]);
        _exit(0);
    }}
    close(pipe_fds[1]);
    dsc_cicd_rate_control_output_t child_output;
    int received = dsc_cicd_read_all(pipe_fds[0], &child_output, sizeof(child_output));
    close(pipe_fds[0]);
    int child_status = 0;
    (void)waitpid(child, &child_status, 0);
    if (!received || !WIFEXITED(child_status) || WEXITSTATUS(child_status) != 0) return 0;
    *output = child_output;
    return 1;
}}
""".strip()


def _overlay_source(info: dict[str, Any], agent: Any) -> str:
    parameters = info["parameters"]
    declaration, names = _parameter_specs(parameters)
    cfg_parameter = next(
        str(item["name"]) for item in parameters if str(item.get("type")) == "dsc_cfg_t *"
    )
    state_parameter = next(
        str(item["name"]) for item in parameters if str(item.get("type")) == "dsc_state_t *"
    )
    scalar_names = [str(item["name"]) for item in parameters if item not in (
        next(item for item in parameters if str(item.get("type")) == "dsc_cfg_t *"),
        next(item for item in parameters if str(item.get("type")) == "dsc_state_t *"),
    )]
    throttle, bpg, group_count, scale, group_size = scalar_names
    original = f"{info['function_name']}_original"
    event_count = len(info["events"])
    _snapshot_apply_source(info)
    input_assignments = _c_input_assignments(info, cfg_parameter, state_parameter)
    apply_rtl = "\n".join(
        f"        {state_parameter}->{field} = dsc_cicd_rtl_output.{_lower_identifier(field)};"
        for field in STATE_OUTPUT_FIELDS
    )
    apply_c = "\n".join(
        f"        {state_parameter}->{field} = dsc_cicd_c_output.{_lower_identifier(field)};"
        for field in STATE_OUTPUT_FIELDS
    )
    c_events = "\n".join(
        f"        if (dsc_cicd_c_output.chunk_write_enable[{index}])\n"
        f"            {state_parameter}->chunkSizes[dsc_cicd_c_output.chunk_write_index[{index}]] = dsc_cicd_c_output.chunk_write_value[{index}];"
        for index in range(event_count)
    )
    rtl_events = "\n".join(
        f"        if (dsc_cicd_rtl_output.chunk_write_enable[{index}])\n"
        f"            {state_parameter}->chunkSizes[dsc_cicd_rtl_output.chunk_write_index[{index}]] = dsc_cicd_rtl_output.chunk_write_value[{index}];"
        for index in range(event_count)
    )
    mismatch_scalar = "\n".join(
        f"    mismatch |= left->{_lower_identifier(field)} != right->{_lower_identifier(field)};"
        for field in STATE_OUTPUT_FIELDS
    )
    mismatch_events = "\n".join(
        f"    mismatch |= left->chunk_write_enable[{index}] != right->chunk_write_enable[{index}];\n"
        f"    if (left->chunk_write_enable[{index}] || right->chunk_write_enable[{index}]) {{\n"
        f"        mismatch |= left->chunk_write_index[{index}] != right->chunk_write_index[{index}];\n"
        f"        mismatch |= left->chunk_write_value[{index}] != right->chunk_write_value[{index}];\n"
        "    }"
        for index in range(event_count)
    )
    # ``agent`` is deliberately not asked to render or execute anything.
    # Keeping this emitter independent is what makes its generated source
    # auditable in isolation.
    _ = agent
    return f"""
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include "dsc_cicd_overlay.h"
#include "dsc_cicd_rtl_abi.h"

extern void {original}({declaration});

{_metrics_source()}

static int dsc_cicd_mode(void) {{
    const char *value = getenv("DSC_CICD_MODE");
    if (value && strcmp(value, "SHADOW") == 0) return 1;
    if (value && strcmp(value, "RTL_RETURN") == 0) return 2;
    return 0; /* C_ONLY, unset, and unknown values are C-only. */
}}

{_state_snapshot_source()}

{_oracle_helpers_source_clean(event_count, original)}

static int dsc_cicd_rate_control_domain(
    const dsc_cfg_t *cfg,
    const dsc_state_t *state,
    int group_count,
    int group_size,
    int event_count) {{
    if (!cfg || !state || !state->chunkSizes || group_count < 0 ||
        state->isEncoder != 1 || group_size < 1 || group_size > event_count ||
        state->unitsPerGroup < 3 || state->unitsPerGroup > DSC_CICD_RC_UNITS ||
        state->prevRange < 0 || state->prevRange >= DSC_CICD_RC_RANGES ||
        state->sliceWidth <= 0 || state->chunkPixelTimes < 0 ||
        state->chunkPixelTimes >= state->sliceWidth || cfg->slice_height <= 0 ||
        state->chunkCount < 0 || state->chunkCount >= cfg->slice_height ||
        cfg->dsc_version_minor < 1 || cfg->dsc_version_minor > 2 ||
        (cfg->native_420 != 0 && cfg->native_420 != 1) ||
        (cfg->native_422 != 0 && cfg->native_422 != 1) ||
        (cfg->native_420 && cfg->native_422) ||
        (cfg->vbr_enable != 0 && cfg->vbr_enable != 1) ||
        cfg->initial_xmit_delay < 0 ||
        state->cpntBitDepth[0] < 8 || state->cpntBitDepth[0] > 16 ||
        state->cpntBitDepth[1] < 8 || state->cpntBitDepth[1] > 16)
        return 0;
    for (int unit = 0; unit < DSC_CICD_RC_UNITS; ++unit)
        if (state->midpointSelected[unit] < 0 || state->midpointSelected[unit] > 1)
            return 0;
    if (state->chunkCount +
            (state->chunkPixelTimes + group_size) / state->sliceWidth >
        cfg->slice_height)
        return 0;
    return 1;
}}

static int dsc_cicd_output_mismatch(
    const dsc_cicd_rate_control_output_t *left,
    const dsc_cicd_rate_control_output_t *right) {{
    int mismatch = 0;
    mismatch |= left->domain_valid != right->domain_valid;
    mismatch |= left->fatal_error != right->fatal_error;
    mismatch |= left->fatal_error_code != right->fatal_error_code;
{mismatch_scalar}
{mismatch_events}
    return mismatch;
}}

static int dsc_cicd_safe_rtl_output(
    const dsc_cicd_rate_control_output_t *output,
    int base,
    int event_count,
    int chunk_capacity) {{
    if (!output->domain_valid || output->fatal_error) return 0;
    int expected_chunk_index = base;
    for (int index = 0; index < event_count; ++index) {{
        if (output->chunk_write_enable[index]) {{
            if (output->chunk_write_index[index] != expected_chunk_index ||
                output->chunk_write_index[index] < 0 ||
                output->chunk_write_index[index] >= chunk_capacity)
                return 0;
            ++expected_chunk_index;
        }}
    }}
    return 1;
}}

void dsc_cicd_invoke({declaration}) {{
    dsc_cicd_note_call();
    dsc_cicd_rate_control_output_t dsc_cicd_c_output;
    dsc_cicd_rate_control_output_t dsc_cicd_rtl_output;
    memset(&dsc_cicd_c_output, 0, sizeof(dsc_cicd_c_output));
    memset(&dsc_cicd_rtl_output, 0, sizeof(dsc_cicd_rtl_output));
    if ({state_parameter} && {state_parameter}->isEncoder != 1) {{
        /* This contract is Encode-specialized; preserve decoder behavior. */
        {original}({', '.join(names)});
        return;
    }}
    if (!{cfg_parameter} || !{state_parameter}) {{
        dsc_cicd_c_output.domain_valid = 0;
        dsc_cicd_c_output.fatal_error = 1;
        dsc_cicd_c_output.fatal_error_code = 1;
        return;
    }}
    dsc_cicd_init_output({state_parameter}, &dsc_cicd_c_output);
    if (!dsc_cicd_rate_control_domain({cfg_parameter}, {state_parameter},
                                      {group_count}, {group_size}, {event_count})) {{
        dsc_cicd_c_output.domain_valid = 0;
        dsc_cicd_c_output.fatal_error = 1;
        dsc_cicd_c_output.fatal_error_code = 1;
        return;
    }}

    dsc_cicd_rate_control_input_t dsc_cicd_input;
    memset(&dsc_cicd_input, 0, sizeof(dsc_cicd_input));
{input_assignments}
    dsc_cicd_rate_control_snapshot_t dsc_cicd_saved;
    dsc_cicd_snapshot_rate_control({state_parameter}, &dsc_cicd_saved);
    int dsc_cicd_chunk_capacity = {cfg_parameter}->slice_height;
    int dsc_cicd_chunk_base = {state_parameter}->chunkCount;
    int dsc_cicd_saved_chunk[DSC_CICD_RC_EVENTS] = {{0}};
    if ((size_t)dsc_cicd_chunk_capacity >
        (size_t)-1 / sizeof(int)) {{
        dsc_cicd_c_output.domain_valid = 0;
        dsc_cicd_c_output.fatal_error = 1;
        dsc_cicd_c_output.fatal_error_code = 4;
        dsc_cicd_restore_rate_control({state_parameter}, &dsc_cicd_saved);
        return;
    }}
    int *dsc_cicd_chunk_shadow = (int *)malloc(
        (size_t)dsc_cicd_chunk_capacity * sizeof(*dsc_cicd_chunk_shadow));
    if (!dsc_cicd_chunk_shadow) {{
        dsc_cicd_c_output.domain_valid = 0;
        dsc_cicd_c_output.fatal_error = 1;
        dsc_cicd_c_output.fatal_error_code = 4;
        dsc_cicd_restore_rate_control({state_parameter}, &dsc_cicd_saved);
        return;
    }}
    for (int chunk = 0; chunk < dsc_cicd_chunk_capacity; ++chunk)
        dsc_cicd_chunk_shadow[chunk] = DSC_CICD_CHUNK_SENTINEL;
    for (int event = 0;
         event < {group_size} && dsc_cicd_chunk_base + event < dsc_cicd_chunk_capacity;
         ++event)
        dsc_cicd_saved_chunk[event] = {state_parameter}->chunkSizes[dsc_cicd_chunk_base + event];

    int dsc_cicd_oracle_ok = dsc_cicd_run_private_oracle(
        {cfg_parameter}, {state_parameter}, {throttle}, {bpg}, {group_count},
        {scale}, {group_size}, dsc_cicd_chunk_base, dsc_cicd_chunk_capacity,
        dsc_cicd_chunk_shadow,
        &dsc_cicd_c_output);
    dsc_cicd_restore_rate_control({state_parameter}, &dsc_cicd_saved);
    for (int event = 0;
         event < {group_size} && dsc_cicd_chunk_base + event < dsc_cicd_chunk_capacity;
         ++event)
        {state_parameter}->chunkSizes[dsc_cicd_chunk_base + event] = dsc_cicd_saved_chunk[event];
    if (!dsc_cicd_oracle_ok) {{
        dsc_cicd_c_output.domain_valid = 0;
        dsc_cicd_c_output.fatal_error = 1;
        dsc_cicd_c_output.fatal_error_code = 2;
    }}

    int mode = dsc_cicd_mode();
    if (mode == 0) {{
        /* C_ONLY commits only the private C oracle footprint. */
        if (!dsc_cicd_c_output.domain_valid || dsc_cicd_c_output.fatal_error) {{
            free(dsc_cicd_chunk_shadow);
            return;
        }}
{apply_c}
{c_events}
        free(dsc_cicd_chunk_shadow);
        return;
    }}
    dsc_cicd_note_rtl_invocation();
    dsc_cicd_rtl(&dsc_cicd_input, &dsc_cicd_rtl_output);
    if (dsc_cicd_output_mismatch(&dsc_cicd_c_output, &dsc_cicd_rtl_output)) {{
        ++dsc_cicd_mismatches;
        if (dsc_cicd_mismatches <= 16) {{
            fprintf(stderr, "C/RTL RateControl Encode mismatch: group=%d size=%d\\n",
                    {group_count}, {group_size});
            fprintf(stderr,
                    "  flags C=%d/%d/%d RTL=%d/%d/%d "
                    "state C=%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d "
                    "RTL=%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d\\n",
                    dsc_cicd_c_output.domain_valid,
                    dsc_cicd_c_output.fatal_error,
                    dsc_cicd_c_output.fatal_error_code,
                    dsc_cicd_rtl_output.domain_valid,
                    dsc_cicd_rtl_output.fatal_error,
                    dsc_cicd_rtl_output.fatal_error_code,
                    dsc_cicd_c_output.bitsavemode,
                    dsc_cicd_c_output.bitsclamped,
                    dsc_cicd_c_output.bpgfracaccum,
                    dsc_cicd_c_output.bufferfullness,
                    dsc_cicd_c_output.chunkcount,
                    dsc_cicd_c_output.chunkpixeltimes,
                    dsc_cicd_c_output.erroroccurred,
                    dsc_cicd_c_output.mppstate,
                    dsc_cicd_c_output.numbitschunk,
                    dsc_cicd_c_output.pixelcount,
                    dsc_cicd_c_output.prevqp,
                    dsc_cicd_c_output.prevrange,
                    dsc_cicd_c_output.rcsizegroup,
                    dsc_cicd_c_output.stqp,
                    dsc_cicd_rtl_output.bitsavemode,
                    dsc_cicd_rtl_output.bitsclamped,
                    dsc_cicd_rtl_output.bpgfracaccum,
                    dsc_cicd_rtl_output.bufferfullness,
                    dsc_cicd_rtl_output.chunkcount,
                    dsc_cicd_rtl_output.chunkpixeltimes,
                    dsc_cicd_rtl_output.erroroccurred,
                    dsc_cicd_rtl_output.mppstate,
                    dsc_cicd_rtl_output.numbitschunk,
                    dsc_cicd_rtl_output.pixelcount,
                    dsc_cicd_rtl_output.prevqp,
                    dsc_cicd_rtl_output.prevrange,
                    dsc_cicd_rtl_output.rcsizegroup,
                    dsc_cicd_rtl_output.stqp);
        }}
    }}
    if (mode == 2) {{
        /* RTL_RETURN commits only validated RTL outputs. */
        if (dsc_cicd_safe_rtl_output(
                &dsc_cicd_rtl_output, dsc_cicd_chunk_base, {group_size},
                dsc_cicd_chunk_capacity)) {{
{apply_rtl}
{rtl_events}
        }}
        free(dsc_cicd_chunk_shadow);
        return;
    }}
    else {{
        /* SHADOW compares RTL but commits the restored C oracle footprint. */
        if (!dsc_cicd_c_output.domain_valid || dsc_cicd_c_output.fatal_error) {{
            free(dsc_cicd_chunk_shadow);
            return;
        }}
{apply_c}
{c_events}
    }}
    free(dsc_cicd_chunk_shadow);
}}

void {info['function_name']}({declaration}) {{
    dsc_cicd_invoke({', '.join(names)});
}}
""".strip()


def _bridge_source(info: dict[str, Any], module: str) -> str:
    safe_module = _safe_identifier(module)
    inputs = info["inputs"]
    output_ports = info["output_ports"]
    argument_ports = info["arguments"]
    config_ports = info["config"]
    state_ports = info["state"]
    input_assignments: list[str] = []
    for port in argument_ports.values():
        input_assignments.append(
            f"    dut.{port} = static_cast<std::uint32_t>(input->{port});"
        )
    for port in config_ports.values():
        input_assignments.append(
            f"    dut.{port} = static_cast<std::uint32_t>(input->{port});"
        )
    for port in state_ports.values():
        input_assignments.append(
            f"    dut.{port} = static_cast<std::uint32_t>(input->{port});"
        )
    input_assignments.extend(
        f"    dut.{port} = static_cast<std::uint32_t>(input->midpoint_selected[{index}]);"
        for index, port in enumerate(info["midpoint"])
    )
    input_assignments.extend(
        f"    dut.{port} = static_cast<std::uint32_t>(input->cpnt_bit_depth[{index}]);"
        for index, port in enumerate(info["depth"])
    )
    input_assignments.extend(
        f"    dut.{port} = static_cast<std::uint32_t>(input->predicted_size[{index}]);"
        for index, port in enumerate(info["predicted"])
    )
    input_assignments.extend(
        f"    dut.{port} = static_cast<std::uint32_t>(input->rc_size_unit[{index}]);"
        for index, port in enumerate(info["rc_size"])
    )
    input_assignments.extend(
        f"    dut.{port} = static_cast<std::uint32_t>(input->rc_buf_thresh[{index}]);"
        for index, port in enumerate(info["thresholds"])
    )
    for field in ("range_min_qp", "range_max_qp", "range_bpg_offset"):
        input_assignments.extend(
            f"    dut.{port} = static_cast<std::uint32_t>(input->{field}[{index}]);"
            for index, port in enumerate(info["ranges"][field])
        )
    output_assignments: list[str] = []
    for field, port in info["fatal"].items():
        output_assignments.append(
            f"    output->{_lower_identifier(field)} = static_cast<std::int32_t>(dut.{port});"
        )
    for field, port in info["outputs"].items():
        output_assignments.append(
            f"    output->{_lower_identifier(field)} = static_cast<std::int32_t>(dut.{port});"
        )
    for index, event in enumerate(info["events"]):
        output_assignments.extend(
            (
                f"    output->chunk_write_enable[{index}] = static_cast<std::int32_t>(dut.{event['enable']});",
                f"    output->chunk_write_index[{index}] = static_cast<std::int32_t>(dut.{event['index']});",
                f"    output->chunk_write_value[{index}] = static_cast<std::int32_t>(dut.{event['value']});",
            )
        )
    expected_input_names = {str(port.get("name")) for port in inputs}
    bound_input_names = {
        *argument_ports.values(),
        *config_ports.values(),
        *state_ports.values(),
        *info["midpoint"],
        *info["depth"],
        *info["predicted"],
        *info["rc_size"],
        *info["thresholds"],
        *[value for values in info["ranges"].values() for value in values],
    }
    if expected_input_names != bound_input_names:
        raise RuntimeError("RateControl bridge input bindings are incomplete")
    return f"""
#include <cstdint>
#include <cstring>
#include "verilated.h"
#include "dsc_cicd_rtl_abi.h"
#include "V{safe_module}.h"

double sc_time_stamp() {{ return 0.0; }}

extern "C" void dsc_cicd_rtl(
    const dsc_cicd_rate_control_input_t *input,
    dsc_cicd_rate_control_output_t *output) {{
    V{safe_module} dut;
    std::memset(output, 0, sizeof(*output));
{chr(10).join(input_assignments)}
    dut.eval();
{chr(10).join(output_assignments)}
}}
""".strip()


def _main_source() -> str:
    return """
#include <stdio.h>
extern int dsc_cicd_original_main(int, char **);
int main(int argc, char **argv) {
    return dsc_cicd_original_main(argc, argv);
}
""".strip()


def write_rate_control_encode_overlay_sources(
    agent: Any,
    contract: dict[str, Any],
    source_dir: pathlib.Path,
    module: str,
    candidate_sv: pathlib.Path,
) -> dict[str, Any]:
    """Write the complete Encode RateControl adapter source set.

    The returned mapping follows ``Agent.write_overlay_sources``: ``header``,
    ``abi``, ``overlay``, ``bridge``, ``main``, and ``candidate`` are paths;
    ``composition`` is the immutable composition receipt used by callers.
    """
    source_dir = pathlib.Path(source_dir)
    candidate_sv = pathlib.Path(candidate_sv)
    info = _validate_contract(agent, contract, source_dir)
    function = contract.get("function", {}) or {}
    function_name = str(function.get("name", ""))
    if not IDENTIFIER.fullmatch(function_name):
        raise RuntimeError("RateControl function name is not a C identifier")
    info["function_name"] = function_name
    safe_module = _safe_identifier(module)
    if not IDENTIFIER.fullmatch(safe_module):
        raise RuntimeError("RTL module name is not a SystemVerilog identifier")
    if candidate_sv.is_file():
        candidate_text = candidate_sv.read_text(encoding="utf-8", errors="replace")
        child_module = str(info["dependency"]["module"])
        stage_matches = re.findall(
            rf"\b{re.escape(child_module)}\s+remove_stage_([0-9]+)\s*\(",
            candidate_text,
        )
        if not 1 <= len(stage_matches) <= MAX_EVENTS:
            raise RuntimeError("RTL must compose one to three pinned RemoveBits stages")
        if sorted(int(value) for value in stage_matches) != list(range(len(stage_matches))):
            raise RuntimeError("RemoveBits stages are not source ordered")
        if "useMidpoint" in candidate_text or "use_midpoint" in candidate_text:
            raise RuntimeError("Encode RTL must not bind decoder midpoint state")
        if not any(port in candidate_text for port in info["midpoint"]):
            raise RuntimeError("Encode RTL midpointSelected ports are not bound")

    header = _write(source_dir / "dsc_cicd_overlay.h", _header_source(info["parameters"]))
    abi = _write(source_dir / "dsc_cicd_rtl_abi.h", _abi_source(info))
    overlay = _write(source_dir / "dsc_cicd_overlay.c", _overlay_source(info, agent))
    bridge = _write(source_dir / "rtl_bridge.cpp", _bridge_source(info, safe_module))
    main = _write(source_dir / "dsc_cicd_main.c", _main_source())

    dependency = info["dependency"]
    config_parameter = str(info["bindings"].get("config_parameter"))
    state_parameter = str(info["bindings"].get("state_parameter"))
    rtl_bindings = [
        *[
            str(item["name"])
            for item in info["parameters"]
            if not (item.get("pointer") or "*" in str(item.get("type", "")))
        ],
        *[f"{config_parameter}->{field}" for field in CONFIG_FIELDS],
        *[f"{state_parameter}->{field}" for field in STATE_FIELDS],
        *[
            f"{state_parameter}->midpointSelected[{index}]"
            for index in range(len(info["midpoint"]))
        ],
        *[
            f"{state_parameter}->cpntBitDepth[{index}]"
            for index in range(len(info["depth"]))
        ],
        *[
            f"{state_parameter}->predictedSize[{index}]"
            for index in range(len(info["predicted"]))
        ],
        *[
            f"{state_parameter}->rcSizeUnit[{index}]"
            for index in range(len(info["rc_size"]))
        ],
        *[
            f"{config_parameter}->rc_buf_thresh[{index}]"
            for index in range(len(info["thresholds"]))
        ],
        *[
            f"{config_parameter}->rc_range_parameters[{index}].{field}"
            for field in ("range_min_qp", "range_max_qp", "range_bpg_offset")
            for index in range(15)
        ],
    ]
    composition = {
        "status": "PASS",
        "adapter_kind": "explicit_bounded_rate_control_encode_transition",
        "caller_parameter_count": len(info["parameters"]),
        "rtl_input_count": len(info["inputs"]),
        "frozen_input_ports": [str(port.get("name")) for port in info["inputs"]],
        "rtl_bindings": rtl_bindings,
        "state_outputs": [str(info["outputs"][field]) for field in STATE_OUTPUT_FIELDS],
        "state_output_count": len(STATE_OUTPUT_FIELDS),
        "chunk_write_events": [dict(event) for event in info["events"]],
        "chunk_write_event_order_is_source_ordered": True,
        "all_config_range_state_inputs_bound": True,
        "all_14_scalar_state_outputs_bound": True,
        "fatal_and_domain_sidebands_compared": True,
        "complete_output_footprint_compared": True,
        "ordered_chunk_events_compared": True,
        "c_oracle_uses_private_embedded_state": True,
        "c_oracle_uses_private_chunk_window": True,
        "c_snapshot_restores_every_touched_scalar_before_mode_selection": True,
        "c_snapshot_restores_every_touched_chunk_byte_before_mode_selection": True,
        "c_only_commits_c": True,
        "shadow_commits_c": True,
        "rtl_return_commits_only_rtl": True,
        "no_c_computed_output_bypass_in_rtl_return": True,
        "actual_verilator_invocation_counted": True,
        "actual_verilator_invocation_is_counted": True,
        "midpoint_selected_encoder_specialization": True,
        "encoder_only_specialization_is_explicit": True,
        "decoder_midpoint_input_not_bound": True,
        "remove_bits_stages_hash_pinned_and_source_ordered": True,
        "three_remove_bits_stages_are_hash_bound_and_ordered": True,
        "remove_bits_function": dependency.get("function", "RemoveBitsEncoderBuffer"),
        "remove_bits_stage_count_max": len(info["events"]),
        "candidate_remove_bits_stage_count": len(
            re.findall(
                rf"\b{re.escape(str(dependency['module']))}\s+remove_stage_[0-9]+\s*\(",
                candidate_sv.read_text(encoding="utf-8", errors="replace")
                if candidate_sv.is_file()
                else "",
            )
        ),
        "remove_bits_dependency": {
            "contract_id": dependency["contract_id"],
            "contract_sha256": dependency["contract_sha256"],
            "module": dependency["module"],
            "module_sha256": dependency["module_sha256"],
        },
        "residual_symbol_alias_routes_to_dispatcher": True,
        "rtl_return_controls_complete_rate_control_scalar_footprint": True,
        "rtl_return_controls_complete_rate_control_scalar_and_chunk_footprint": True,
        "chunk_pointer_and_output_indices_are_bounds_checked": True,
    }
    return {
        "header": header,
        "abi": abi,
        "overlay": overlay,
        "bridge": bridge,
        "main": main,
        "candidate": candidate_sv,
        "composition": composition,
    }


__all__ = ["write_rate_control_encode_overlay_sources"]
