module estimatebitsforgroup_interface (
    input logic [1:0] dsc_version_minor,
    input logic native_420,
    input logic [2:0] units_per_group,
    input logic [1:0] pixels_in_group,
    input logic [15:0] hPos,
    input logic [15:0] slice_width,
    input logic prev_ich_selected,
    input logic [4:0] primary_qp,
    input logic [4:0] prev_primary_qp,
    input logic [4:0] cpntBitDepth_0,
    input logic [4:0] cpntBitDepth_1,
    input logic [4:0] cpntBitDepth_2,
    input logic [4:0] cpntBitDepth_3,
    input logic [1:0] unit_c_type_0,
    input logic [1:0] unit_c_type_1,
    input logic [1:0] unit_c_type_2,
    input logic [1:0] unit_c_type_3,
    input logic [15:0] unit_start_h_pos_0,
    input logic [15:0] unit_start_h_pos_1,
    input logic [15:0] unit_start_h_pos_2,
    input logic [15:0] unit_start_h_pos_3,
    input logic [4:0] predicted_size_0,
    input logic [4:0] predicted_size_1,
    input logic [4:0] predicted_size_2,
    input logic [4:0] predicted_size_3,
    input logic signed [16:0] quantized_residual_0_0,
    input logic signed [16:0] quantized_residual_0_1,
    input logic signed [16:0] quantized_residual_0_2,
    input logic signed [16:0] quantized_residual_1_0,
    input logic signed [16:0] quantized_residual_1_1,
    input logic signed [16:0] quantized_residual_1_2,
    input logic signed [16:0] quantized_residual_2_0,
    input logic signed [16:0] quantized_residual_2_1,
    input logic signed [16:0] quantized_residual_2_2,
    input logic signed [16:0] quantized_residual_3_0,
    input logic signed [16:0] quantized_residual_3_1,
    input logic signed [16:0] quantized_residual_3_2,
    input logic [4:0] qlevel_luma_new,
    input logic [4:0] qlevel_luma_old,
    input logic [4:0] qlevel_chroma_new,
    input logic [4:0] qlevel_chroma_old,
    output logic [8:0] return_value
);
endmodule
